/*******************************************************************************
 * SPDX-License-Identifier: EUPL-1.2
 * Copyright Regione Piemonte - 2020
 *******************************************************************************/

GRANT ALTER, SELECT ON SEQ_SICEE_T_FOTO_2015 TO SICEE_RW;
GRANT ALTER, SELECT ON SEQ_SICEE_T_RIF_INDEX_2015 TO SICEE_RW;
GRANT ALTER, SELECT ON SEQ_SICEE_T_QTA_CONSUMI_2015 TO SICEE_RW;
GRANT ALTER, SELECT ON SEQ_SICEE_T_RACCOMAND_2015 TO SICEE_RW;
GRANT ALTER, SELECT ON SEQ_SICEE_T_DET_IMP_2015 TO SICEE_RW;

GRANT SELECT,UPDATE,DELETE,INSERT ON SICEE_D_DEST_USO_2015  TO SICEE_RW;
GRANT SELECT,UPDATE,DELETE,INSERT ON SICEE_D_OGGETTO_APE_2015 TO SICEE_RW;
GRANT SELECT,UPDATE,DELETE,INSERT ON SICEE_D_RIQ_ENER_2015 TO SICEE_RW;
GRANT SELECT,UPDATE,DELETE,INSERT ON SICEE_D_RUOLO_CERT_2015 TO SICEE_RW;
GRANT SELECT,UPDATE,DELETE,INSERT ON SICEE_D_SERV_ENER_2015 TO SICEE_RW;
GRANT SELECT,UPDATE,DELETE,INSERT ON SICEE_D_TIPO_COPERT_2015 TO SICEE_RW;
GRANT SELECT,UPDATE,DELETE,INSERT ON SICEE_D_TIPO_DOC_INDEX_2015 TO SICEE_RW;
GRANT SELECT,UPDATE,DELETE,INSERT ON SICEE_D_TIPO_FOTO_2015 TO SICEE_RW;
GRANT SELECT,UPDATE,DELETE,INSERT ON SICEE_D_TIPO_OMBREG_2015 TO SICEE_RW;
GRANT SELECT,UPDATE,DELETE,INSERT ON SICEE_D_TIPO_STRUT_2015 TO SICEE_RW;
GRANT SELECT,UPDATE,DELETE,INSERT ON SICEE_D_TIPO_TELAIO_2015 TO SICEE_RW;
GRANT SELECT,UPDATE,DELETE,INSERT ON SICEE_D_TIPO_VETRO_2015 TO SICEE_RW;
GRANT SELECT,UPDATE,DELETE,INSERT ON SICEE_D_UNITA_MISURA_2015 TO SICEE_RW;
GRANT SELECT,UPDATE,DELETE,INSERT ON SICEE_D_ZONA_CLIMATICA_2015 TO SICEE_RW;
GRANT SELECT,UPDATE,DELETE,INSERT ON SICEE_R_COMB_DENER_2015 TO SICEE_RW;
GRANT SELECT,UPDATE,DELETE,INSERT ON SICEE_R_DETT_COP_2015 TO SICEE_RW;
GRANT SELECT,UPDATE,DELETE,INSERT ON SICEE_R_DETT_INFISSI_2015 TO SICEE_RW;
GRANT SELECT,UPDATE,DELETE,INSERT ON SICEE_R_DETT_STRUT_2015 TO SICEE_RW;
GRANT SELECT,UPDATE,DELETE,INSERT ON SICEE_T_CERT_XML_2015 TO SICEE_RW;
GRANT SELECT,UPDATE,DELETE,INSERT ON SICEE_T_DATI_ENER_2015 TO SICEE_RW;
GRANT SELECT,UPDATE,DELETE,INSERT ON SICEE_T_CREDITO TO SICEE_RW;
GRANT SELECT,UPDATE,DELETE,INSERT ON SICEE_T_DET_IMP_2015 TO SICEE_RW;
GRANT SELECT,UPDATE,DELETE,INSERT ON SICEE_T_FOTO_2015 TO SICEE_RW;
GRANT SELECT,UPDATE,DELETE,INSERT ON SICEE_T_QTA_CONSUMI_2015 TO SICEE_RW;
GRANT SELECT,UPDATE,DELETE,INSERT ON SICEE_T_RACCOMAND_2015 TO SICEE_RW;
GRANT SELECT,UPDATE,DELETE,INSERT ON SICEE_T_RIF_INDEX_2015 TO SICEE_RW;
GRANT SELECT,UPDATE,DELETE,INSERT ON SICEE_D_SCADENZA_CERT_2015 TO SICEE_RW;

