/*******************************************************************************
 * SPDX-License-Identifier: EUPL-1.2
 * Copyright Regione Piemonte - 2020
 *******************************************************************************/

GRANT ALTER, SELECT ON SEQ_SICEE_T_DATI_ESAMI TO SICEE_RW;
GRANT ALTER, SELECT ON SEQ_SICEE_T_DATI_FIRMA TO SICEE_RW;
GRANT ALTER, SELECT ON SEQ_SICEE_T_PROGR_VER_REPORT TO SICEE_RW;


GRANT SELECT,UPDATE,DELETE,INSERT ON SICEE_T_DATI_ESAMI TO SICEE_RW;
GRANT SELECT,UPDATE,DELETE,INSERT ON SICEE_D_STATO_FILE TO SICEE_RW;
GRANT SELECT,UPDATE,DELETE,INSERT ON SICEE_T_DATI_FIRMA TO SICEE_RW;
GRANT SELECT,UPDATE,DELETE,INSERT ON SICEE_T_ESAMI TO SICEE_RW;
GRANT SELECT,UPDATE,DELETE,INSERT ON SICEE_T_VERIFY_REPORT TO SICEE_RW;
GRANT SELECT,UPDATE,DELETE,INSERT ON SICEE_D_MAPPING_XML TO SICEE_RW;



