/*******************************************************************************
 * SPDX-License-Identifier: EUPL-1.2
 * Copyright Regione Piemonte - 2020
 *******************************************************************************/
GRANT SELECT,UPDATE,DELETE,INSERT ON SICEE_D_PROPRIETA_EDIF_2015 TO SICEE_RW;
GRANT SELECT,UPDATE,DELETE,INSERT ON SICEE_D_TIPO_RISTRUTT_2015 TO SICEE_RW;
GRANT SELECT,UPDATE,DELETE,INSERT ON SICEE_D_TIPO_VENTILAZIONE_2015 TO SICEE_RW;
GRANT SELECT,UPDATE,DELETE,INSERT ON SICEE_D_TIPOL_COSTRUTT_2015 TO SICEE_RW;
GRANT SELECT,UPDATE,DELETE,INSERT ON SICEE_D_TIPOL_EDILIZIA_2015 TO SICEE_RW;
GRANT SELECT,UPDATE,DELETE,INSERT ON SICEE_T_DATI_XML_2015 TO SICEE_RW;
GRANT SELECT,UPDATE,DELETE,INSERT ON SICEE_T_DATI_XML_ED_REALE_2015 TO SICEE_RW;
GRANT SELECT,UPDATE,DELETE,INSERT ON SICEE_T_DATI_XML_ED_RIF_2015 TO SICEE_RW;

GRANT SELECT,UPDATE,DELETE,INSERT ON SICEE_T_IMPDATI_XML_2015 TO SICEE_RW;


GRANT SELECT,UPDATE,DELETE,INSERT ON SICEE_R_CERTIF_SERVENER2015 TO SICEE_RW;
GRANT SELECT,UPDATE,DELETE,INSERT ON SICEE_T_DET_IMP_2015_BCK TO SICEE_RW;
