/*******************************************************************************
 * SPDX-License-Identifier: EUPL-1.2
 * Copyright Regione Piemonte - 2020
 *******************************************************************************/

GRANT SELECT,UPDATE,DELETE,INSERT ON SICEE_T_RIMBORSI_ACE TO SICEE_RW;
GRANT SELECT,UPDATE,DELETE,INSERT ON SICEE_T_HD_ACE_FIRMATI TO SICEE_RW;
GRANT SELECT,UPDATE,DELETE,INSERT ON SICEE_L_LOG_ATTIVITA TO SICEE_RW;
GRANT SELECT,UPDATE,DELETE,INSERT ON SICEE_T_APPOGGIO TO SICEE_RW;

GRANT SELECT,ALTER ON SEQ_SICEE_T_HD_ACE_FIRMATI TO SICEE_RW;
GRANT SELECT,ALTER ON SEQ_SICEE_T_APPOGGIO TO SICEE_RW;
GRANT SELECT,ALTER ON SEQ_SICEE_T_RIMBORSI_ACE TO SICEE_RW;



