/*******************************************************************************
 * SPDX-License-Identifier: EUPL-1.2
 * Copyright Regione Piemonte - 2020
 *******************************************************************************/
ALTER TABLE SICEE_T_TRANSAZIONE_ACE ADD FK_CERTIFICATORE VARCHAR2(5);
ALTER TABLE SICEE_T_TRANSAZIONE_ACE ADD ANNO VARCHAR2(4);
ALTER TABLE SICEE_T_TRANSAZIONE_ACE ADD QUANTITA NUMBER(6);

ALTER TABLE SICEE_T_TRANSAZIONE_REGISTRAZ ADD ANNO VARCHAR2(4);
ALTER TABLE SICEE_T_TRANSAZIONE_REGISTRAZ ADD QUANTITA NUMBER(6);

ALTER TABLE SICEE_T_CERTIFICATO MODIFY NUM_COCERTIFICATORE VARCHAR2(6);


