/*******************************************************************************
 * SPDX-License-Identifier: EUPL-1.2
 * Copyright Regione Piemonte - 2020
 *******************************************************************************/

CREATE TABLE SICEE_T_DATICATAST_SEC (
       ID_DATICATAST_SEC    NUMBER(6) NOT NULL,
       ID_CERTIFICATORE     VARCHAR2(5) NOT NULL,
       PROGR_CERTIFICATO    VARCHAR2(4) NOT NULL,
       ANNO                 VARCHAR2(4) NOT NULL,
       SEZIONE              VARCHAR2(5) NULL,
       FOGLIO               VARCHAR2(5) NULL,
       PARTICELLA           VARCHAR2(9) NULL,
       SUBALTERNO           VARCHAR2(4) NULL,
       FLG_SIGMATER         CHAR(1) NULL,
       ID_PROV              VARCHAR2(6) NULL,
       DESC_PROV            VARCHAR2(50) NULL,
       ID_COMUNE            VARCHAR2(6) NULL,
       DESC_COMUNE          VARCHAR2(50) NULL
)
       TABLESPACE SICEE_SMALL_TBL
;


ALTER TABLE SICEE_T_DATICATAST_SEC
       ADD  ( CONSTRAINT PK_SICEE_T_DATICATAST_SEC PRIMARY KEY (
              ID_DATICATAST_SEC)
       USING INDEX
              TABLESPACE SICEE_SMALL_IDX ) ;

ALTER TABLE SICEE_T_DATICATAST_SEC
       ADD  ( CONSTRAINT FK_SICEE_T_CERTIFICATO_16
              FOREIGN KEY (ID_CERTIFICATORE, PROGR_CERTIFICATO, ANNO)
                             REFERENCES SICEE_T_CERTIFICATO ) ;
                             
        

CREATE TABLE SICEE_T_DATI_BATCH (
       ID_DATI_BATCH        NUMBER NOT NULL,
       ID_CERTIFICATORE     VARCHAR2(5) NOT NULL,
       PROGR_CERTIFICATO    VARCHAR2(4) NOT NULL,
       ANNO                 VARCHAR2(4) NOT NULL,
       PROGR_VERIFY_REPORT  NUMBER(6) NOT NULL
)
       TABLESPACE SICEE_SMALL_TBL
;


ALTER TABLE SICEE_T_DATI_BATCH
       ADD  ( CONSTRAINT PK_SICEE_T_DATI_BATCH PRIMARY KEY (
              ID_DATI_BATCH)
       USING INDEX
              TABLESPACE SICEE_SMALL_IDX ) ;


ALTER TABLE SICEE_T_DATI_BATCH
       ADD  ( CONSTRAINT FK_SICEE_T_VERIFY_REPORT_02
              FOREIGN KEY (ID_CERTIFICATORE, PROGR_CERTIFICATO, ANNO, 
              PROGR_VERIFY_REPORT)
                             REFERENCES SICEE_T_VERIFY_REPORT ) ;
                             

ALTER TABLE SICEE_T_VERIFY_REPORT ADD DATA_BATCH DATE;                          


CREATE TABLE SICEE_L_LOG_BATCH (
       ID_LOG_BATCH         NUMBER NOT NULL,
       NOME_BATCH           VARCHAR2(50) NULL,
       DATA_INIZIO_BATCH    DATE NULL,
       DATA_FINE_BATCH      DATE NULL,
       NOME_ANOMALIA        VARCHAR2(2000) NULL
)
       TABLESPACE SICEE_SMALL_TBL
;


ALTER TABLE SICEE_L_LOG_BATCH
       ADD  ( CONSTRAINT PK_SICEE_L_LOG_BATCH PRIMARY KEY (
              ID_LOG_BATCH)
       USING INDEX
              TABLESPACE SICEE_SMALL_IDX ) ;



CREATE TABLE SICEE_T_EXPORT_BO (
       ID_CERTIFICATORE     VARCHAR2(5) NOT NULL,
       PROGR_CERTIFICATO    VARCHAR2(4) NOT NULL,
       ANNO                 VARCHAR2(4) NOT NULL,
       DT_INIZIO            DATE NULL,
       DT_UPLOAD            DATE NULL,
       DESC_PROV            VARCHAR2(50) NULL,
       DESC_COMUNE          VARCHAR2(50) NULL,
       GRADI_GIORNO         NUMBER(6) NULL,
       PIANO                NUMBER(3) NULL,
       NUM_PIANI_COMPLESSIVI NUMBER(3) NULL,
       FK_STATO             NUMBER(3) NULL,
       FK_DEST_USO          NUMBER(3) NULL,
       DESC_TIPO_EDIFICIO   VARCHAR2(100) NULL,
       FK_EDIFICIO          NUMBER(6) NULL,
       FK_CLASSE            NUMBER(3) NULL,
       ANNO_COSTRUZIONE     NUMBER(4) NULL,
       ANNO_ULT_RIST        NUMBER(4) NULL,
       VOL_LORDO_RISCALDATO NUMBER(14,4) NULL,
       SUP_DISPERDENTE_TOT  NUMBER(14,4) NULL,
       SU                   NUMBER(14,4) NULL,
       TRASM_OPACHE         NUMBER(14,4) NULL,
       TRASM_TRASP          NUMBER(14,4) NULL,
       FATTORE_FORMA        NUMBER(14,4) NULL,
       V_SU                 NUMBER(14,4) NULL,
       DOM_RISC_QHTO        NUMBER(14,4) NULL,
       IND_RISC_EPITO       NUMBER(14,4) NULL,
       FLG_FABB_MAX_INDICE  CHAR(1) NULL,
       VALORE_PREST_PDC     NUMBER(14,4) NULL,
       REND_ACS_ETAGACS     NUMBER(17,5) NULL,
       DOM_ACS_QHW          NUMBER(14,4) NULL,
       EN_ACS_RINNO         NUMBER(14,4) NULL,
       REND_IMP_ETAG        NUMBER(14,4) NULL,
       DOM_ACS_QHW_SU       NUMBER(14,4) NULL,
       IND_GLOB_EPLORDO     NUMBER(14,4) NULL,
       DOM_ACS_QHWTO        NUMBER(14,4) NULL,
       FLG_FABB_ACS         CHAR(1) NULL,
       FK_MOTIVO            NUMBER(3) NULL,
       METODOLOGIA_CALCOLO  VARCHAR2(100) NULL,
       SW_UTILIZZATO        VARCHAR2(100) NULL,
       DESC_INDIRIZZO       VARCHAR2(160) NULL,
       NUM_CIVICO           VARCHAR2(10) NULL,
       SEZIONE              VARCHAR2(5) NULL,
       FOGLIO               VARCHAR2(5) NULL,
       PARTICELLA           VARCHAR2(9) NULL,
       SUBALTERNO           VARCHAR2(4) NULL,
       ID_PROV              VARCHAR2(6) NULL,
       ID_COMUNE            VARCHAR2(6) NULL
)
       TABLESPACE SICEE_SMALL_TBL
;


ALTER TABLE SICEE_T_EXPORT_BO
       ADD  ( CONSTRAINT PK_SICEE_T_EXPORT_BO PRIMARY KEY (
              ID_CERTIFICATORE, PROGR_CERTIFICATO, ANNO)
       USING INDEX
              TABLESPACE SICEE_SMALL_IDX ) ;


CREATE TABLE SICEE_D_EDIFICIO (
       ID_EDIFICIO          NUMBER(6) NOT NULL,
       DESCR                VARCHAR2(100) NULL
)
       TABLESPACE SICEE_SMALL_TBL
;


ALTER TABLE SICEE_D_EDIFICIO
       ADD  ( CONSTRAINT PK_SICEE_D_EDIFICIO PRIMARY KEY (ID_EDIFICIO)
       USING INDEX
              TABLESPACE SICEE_SMALL_IDX ) ;
              
ALTER TABLE SICEE_T_DATI_GENERALI ADD FK_EDIFICIO  NUMBER(6);


ALTER TABLE SICEE_T_DATI_GENERALI
       ADD  ( CONSTRAINT FK_SICEE_D_EDIFICIO_01
              FOREIGN KEY (FK_EDIFICIO)
                             REFERENCES SICEE_D_EDIFICIO ) ;              
  
  
ALTER TABLE SICEE_T_EXPORT_BO
       ADD  ( CONSTRAINT FK_SICEE_T_CERTIFICATO_17
              FOREIGN KEY (ID_CERTIFICATORE, PROGR_CERTIFICATO, ANNO)
                             REFERENCES SICEE_T_CERTIFICATO ) ;

  
              
              
ALTER TABLE SICEE_D_STATO_CERT ADD FLG_RICERCA CHAR(1);

ALTER TABLE SICEE_D_DEST_USO ADD FLG_RICERCA CHAR(1);


UPDATE SICEE_D_DEST_USO SET FLG_RICERCA='S'
WHERE SIGLA NOT LIKE '%(%)%';

COMMIT;

Insert into SICEE_D_STATO_CERT
   (ID_STATO, DESCR)
 Values
   (4, 'Annullato');
COMMIT;

UPDATE SICEE_D_STATO_CERT SET FLG_RICERCA='S' WHERE ID_STATO IN (3);

COMMIT;
                             