/*******************************************************************************
 * SPDX-License-Identifier: EUPL-1.2
 * Copyright Regione Piemonte - 2020
 *******************************************************************************/

CREATE TABLE SICEE_D_TIPO_ISTRUZIONE (
       ID_TIPO_ISTRUZIONE   NUMBER(3) NOT NULL,
       DESCR                VARCHAR2(100) NULL
);


ALTER TABLE SICEE_D_TIPO_ISTRUZIONE
       ADD  ( CONSTRAINT PK_SICEE_D_TIPO_ISTRUZIONE PRIMARY KEY (
              ID_TIPO_ISTRUZIONE) ) ;
              
CREATE TABLE SICEE_D_ISTRUZIONE (
       ID_ISTRUZIONE        NUMBER(3) NOT NULL,
       FK_TIPO_ISTRUZIONE   NUMBER(3) NOT NULL,
       CODICE               VARCHAR2(100) NULL,
       DENOMINAZIONE        VARCHAR2(200) NULL,
       SIGLA_ORDINE         CHAR(1) NULL,
       SIGLA_NON_ORDINE     CHAR(1) NULL
);


ALTER TABLE SICEE_D_ISTRUZIONE
       ADD  ( CONSTRAINT PK_SICEE_D_ISTRUZIONE PRIMARY KEY (
              ID_ISTRUZIONE) ) ;


CREATE TABLE SICEE_T_ESAME_DPR75 (
       ID_DATI_ESAMI        NUMBER(6) NOT NULL,
       FK_CERTIFICATORE     VARCHAR2(5) NOT NULL,
       CORSO_FREQUENTATO    VARCHAR2(1000) NULL,
       DT_DAL               DATE NULL,
       DT_AL                DATE NULL,
       TOTALE_ORE           NUMBER(5) NULL,
       ESAME_PRESSO         VARCHAR2(1000) NULL,
       DT_ESAME             DATE NULL,
       ATTESTATO_PRESSO     VARCHAR2(1000) NULL,
       DT_ATTESTATO         DATE NULL
)
       TABLESPACE SICEE_SMALL_TBL
;


ALTER TABLE SICEE_T_ESAME_DPR75
       ADD  ( CONSTRAINT PK_SICEE_T_DATI_ESAME_DPR75 PRIMARY KEY (
              ID_DATI_ESAMI)
       USING INDEX
              TABLESPACE SICEE_SMALL_IDX ) ;
              

ALTER TABLE SICEE_T_CERTIFICATORE ADD FK_ISTRUZIONE NUMBER(3);                       
ALTER TABLE SICEE_T_CERTIFICATORE ADD FLG_AGG_DATI CHAR(1);       
ALTER TABLE SICEE_T_CERTIFICATORE ADD FLG_AGG_EMAIL CHAR(1);       
ALTER TABLE SICEE_T_CERTIFICATORE ADD DT_AGG_DATI DATE;       
ALTER TABLE SICEE_T_CERTIFICATORE ADD DT_AGG_EMAIL DATE;       
ALTER TABLE SICEE_T_CERTIFICATORE ADD ISCRITTO_ORDINE CHAR(1);
ALTER TABLE SICEE_T_CERTIFICATORE ADD COMPETENZE_NAZIONALI CHAR(1);       
ALTER TABLE SICEE_T_CERTIFICATORE ADD ACCETTAZIONE_TECNICO CHAR(1); 


ALTER TABLE SICEE_D_ISTRUZIONE
       ADD  ( CONSTRAINT FK_SICEE_D_TIPO_ISTRUZIONE_01
              FOREIGN KEY (FK_TIPO_ISTRUZIONE)
                             REFERENCES SICEE_D_TIPO_ISTRUZIONE ) ;
                             
ALTER TABLE SICEE_T_CERTIFICATORE
       ADD  ( CONSTRAINT FK_SICEE_D_ISTRUZIONE_01
              FOREIGN KEY (FK_ISTRUZIONE)
                             REFERENCES SICEE_D_ISTRUZIONE ) ;

ALTER TABLE SICEE_T_ESAME_DPR75
       ADD  ( CONSTRAINT FK_SICEE_T_CERTIFICATORE_06
              FOREIGN KEY (FK_CERTIFICATORE)
                             REFERENCES SICEE_T_CERTIFICATORE ) ;                             


CREATE SEQUENCE SEQ_SICEE_T_ESAME_DPR75 START WITH 1 NOMAXVALUE MINVALUE 1 NOCYCLE NOCACHE NOORDER;


update SICEE_T_CERTIFICATORE set FLG_AGG_DATI = 'N';
commit;

update SICEE_T_CERTIFICATORE set FLG_AGG_EMAIL = 'N';
commit;


SET DEFINE OFF;
Insert into SICEE.SICEE_D_TIPO_DOCUMENTO
   (ID_TIPO_DOC, DS_TIPO_DOC)
 Values
   (2, 'PARTECIPAZ_REGIONALE');
Insert into SICEE.SICEE_D_TIPO_DOCUMENTO
   (ID_TIPO_DOC, DS_TIPO_DOC)
 Values
   (3, 'PROFITTO_REGIONALE');
Insert into SICEE.SICEE_D_TIPO_DOCUMENTO
   (ID_TIPO_DOC, DS_TIPO_DOC)
 Values
   (4, 'PROFITTO_NAZIONALE');
COMMIT;


ALTER TABLE SICEE_T_CERTIFICATORE ADD DT_EMAIL_VERIFICA  DATE;



/* MODIFICHE 1/10/2014 */


CREATE TABLE SICEE_T_VERIFY_REPORT_OLD (
       ID_CERTIFICATORE     VARCHAR2(5) NOT NULL,
       PROGR_CERTIFICATO    VARCHAR2(4) NOT NULL,
       ANNO                 VARCHAR2(4) NOT NULL,
       PROGR_VERIFY_REPORT  NUMBER(6) NOT NULL,
       PARAMETRI_INPUT      NUMBER(3) NULL,
       FORMATO_FIRMA        NUMBER(3) NULL,
       TIPO_FIRMA           NUMBER(3) NULL,
       NUM_CERTIFICATI_FIRMA NUMBER(3) NULL,
       NUM_MARCHE           NUMBER(3) NULL,
       DATA_BATCH           DATE NULL
)
      TABLESPACE SICEE_SMALL_TBL
 ;

ALTER TABLE SICEE_T_VERIFY_REPORT_OLD
       ADD  ( CONSTRAINT PK_SICEE_T_VERIFY_REP_OLD PRIMARY KEY (
              ID_CERTIFICATORE, PROGR_CERTIFICATO, ANNO, 
              PROGR_VERIFY_REPORT) ) ;


CREATE TABLE SICEE_T_DATI_FIRMA_OLD (
       ID_DATI_FIRMA        NUMBER(6) NOT NULL,
       ID_CERTIFICATORE     VARCHAR2(5) NOT NULL,
       PROGR_CERTIFICATO    VARCHAR2(4) NOT NULL,
       ANNO                 VARCHAR2(4) NOT NULL,
       PROGR_VERIFY_REPORT  NUMBER(6) NULL,
       FK_STATO_FILE        NUMBER(3) NOT NULL,
       ERROR_CODE           NUMBER(3) NULL,
       SURNAME              VARCHAR2(100) NULL,
       GIVEN_NAME           VARCHAR2(100) NULL,
       SERIAL_NUMBER        VARCHAR2(100) NULL,
       CA                   VARCHAR2(100) NULL,
       CODICE_FISCALE       VARCHAR2(16) NULL,
       DT_FIRMA             DATE NULL,
       DT_VERIFICA          DATE NULL,
       DT_INIZIO_VAL_CERT   DATE NULL,
       DT_FINE_VAL_CERT     DATE NULL
)
      TABLESPACE SICEE_SMALL_TBL
 ;


ALTER TABLE SICEE_T_DATI_FIRMA_OLD
       ADD  ( CONSTRAINT PK_SICEE_T_DATI_FIRMA_OLD PRIMARY KEY (
              ID_DATI_FIRMA) ) ;


ALTER TABLE SICEE_T_DATI_FIRMA_OLD
       ADD  ( CONSTRAINT FK_SICEE_T_VERIFY_REP_OLD_01
              FOREIGN KEY (ID_CERTIFICATORE, PROGR_CERTIFICATO, ANNO, 
              PROGR_VERIFY_REPORT)
                             REFERENCES SICEE_T_VERIFY_REPORT_OLD ) ;



ALTER TABLE SICEE_T_DATI_FIRMA_OLD
       ADD  ( CONSTRAINT FK_SICEE_D_STATO_FILE_02
              FOREIGN KEY (FK_STATO_FILE)
                             REFERENCES SICEE_D_STATO_FILE ) ;


ALTER TABLE SICEE_T_VERIFY_REPORT_OLD
       ADD  ( CONSTRAINT FK_SICEE_T_CERTIFICATO_21
              FOREIGN KEY (ID_CERTIFICATORE, PROGR_CERTIFICATO, ANNO)
                             REFERENCES SICEE_T_CERTIFICATO ) ;

                             




