/*******************************************************************************
 * SPDX-License-Identifier: EUPL-1.2
 * Copyright Regione Piemonte - 2020
 *******************************************************************************/

CREATE INDEX IE_SICEE_T_CERTIFICATO_01 ON SICEE_T_CERTIFICATO
(FK_TRANSAZIONE_ACE)
TABLESPACE SICEE_SMALL_IDX;

CREATE INDEX IE_SICEE_T_DATICATAST_SEC_01 ON SICEE_T_DATICATAST_SEC
(ID_CERTIFICATORE,PROGR_CERTIFICATO,ANNO)
TABLESPACE SICEE_SMALL_IDX;

CREATE INDEX IE_SICEE_T_CERTIFICATORE_01 ON SICEE_T_CERTIFICATORE
(NUM_CERTIFICATORE)
TABLESPACE SICEE_SMALL_IDX;

