/*******************************************************************************
 * SPDX-License-Identifier: EUPL-1.2
 * Copyright Regione Piemonte - 2020
 *******************************************************************************/

CREATE SEQUENCE SEQ_SICEE_L_ANOMALIE_BATCH START WITH 1 NOMAXVALUE MINVALUE 1 NOCYCLE NOCACHE NOORDER;
CREATE SEQUENCE SEQ_SICEE_T_SOSTITUZIONE_PROGR START WITH 1 NOMAXVALUE MINVALUE 1 NOCYCLE NOCACHE NOORDER;
CREATE SEQUENCE SEQ_SICEE_T_SOSTITUZIONE_ID START WITH 1 NOMAXVALUE MINVALUE 1 NOCYCLE NOCACHE NOORDER;
CREATE SEQUENCE SEQ_SICEE_T_DICHIARAZIONE_SOST START WITH 1 NOMAXVALUE MINVALUE 1 NOCYCLE NOCACHE NOORDER;


