/*******************************************************************************
 * SPDX-License-Identifier: EUPL-1.2
 * Copyright Regione Piemonte - 2020
 *******************************************************************************/

GRANT SELECT,UPDATE,DELETE,INSERT ON COMUNI TO SICEE_RW;
GRANT SELECT,UPDATE,DELETE,INSERT ON PROVINCE TO SICEE_RW;
GRANT SELECT,UPDATE,DELETE,INSERT ON REGIONI TO SICEE_RW;

GRANT SELECT,UPDATE,DELETE,INSERT ON SICEE_D_STATO_MDP TO SICEE_RW;

GRANT SELECT ON OD_SICEE_ACE_ANNOCOSTR_VOLUME TO SICEE_RW;
GRANT SELECT ON OD_SICEE_ACE_COMBUSTIBILE TO SICEE_RW;
GRANT SELECT ON OD_SICEE_ACE_COMUNE_CLASSE TO SICEE_RW;
GRANT SELECT ON OD_SICEE_ACE_DEST_USO TO SICEE_RW;
GRANT SELECT ON OD_SICEE_ACE_MOTIVO_RIL TO SICEE_RW;
GRANT SELECT ON OD_SICEE_ACE_TIPO_IMPIANTO TO SICEE_RW;
GRANT SELECT ON OD_SICEE_ANNOCOSTR_CLASSE TO SICEE_RW;
GRANT SELECT ON OD_SICEE_CERTIFICATORI_TITOLO TO SICEE_RW;

