/*******************************************************************************
 * SPDX-License-Identifier: EUPL-1.2
 * Copyright Regione Piemonte - 2020
 *******************************************************************************/

GRANT SELECT,UPDATE,DELETE,INSERT ON SICEE_L_ANOMALIE_BATCH TO SICEE_RW;
GRANT SELECT,UPDATE,DELETE,INSERT ON SICEE_D_PARAMETRI_SOST TO SICEE_RW;
GRANT SELECT,UPDATE,DELETE,INSERT ON SICEE_D_MOTIVO_SOST TO SICEE_RW;
GRANT SELECT,UPDATE,DELETE,INSERT ON SICEE_R_MOTIVO_PARAM TO SICEE_RW;
GRANT SELECT,UPDATE,DELETE,INSERT ON SICEE_T_DICHIARAZIONE_SOST TO SICEE_RW;
GRANT SELECT,UPDATE,DELETE,INSERT ON SICEE_T_SOSTITUZIONE TO SICEE_RW;
GRANT SELECT,UPDATE,DELETE,INSERT ON SICEE_D_TIPO_EDIFICIO TO SICEE_RW;

GRANT SELECT ON V_ACE_ANNOCOSTR_CLASSE TO SICEE_RW;
GRANT SELECT ON V_ACE_COMUNE_CLASSE TO SICEE_RW;
 



GRANT ALTER,SELECT ON SEQ_SICEE_L_ANOMALIE_BATCH TO SICEE_RW;
GRANT ALTER,SELECT ON SEQ_SICEE_T_SOSTITUZIONE_PROGR TO SICEE_RW;
GRANT ALTER,SELECT ON SEQ_SICEE_T_SOSTITUZIONE_ID TO SICEE_RW;
GRANT ALTER,SELECT ON SEQ_SICEE_T_DICHIARAZIONE_SOST TO SICEE_RW;


