/*******************************************************************************
 * SPDX-License-Identifier: EUPL-1.2
 * Copyright Regione Piemonte - 2020
 *******************************************************************************/
CREATE TABLE SICEE_T_DET_IMP_2015_BCK as select * from SICEE_T_DET_IMP_2015;



ALTER TABLE SICEE_T_CERTIFICATO ADD (NUM_PIANI_FT_RISC  NUMBER(3));

ALTER TABLE SICEE_T_DATI_GENERALI ADD (FK_TIPO_RISTRUTTURAZ  NUMBER(3));
ALTER TABLE SICEE_T_DATI_GENERALI ADD (FK_TIPOL_EDILIZIA  NUMBER(3));
ALTER TABLE SICEE_T_DATI_GENERALI ADD (FK_TIPOL_COSTRUTTIVA  NUMBER(3));



-----------------------------------------------------
-- Richiesta di Reineri del 03/03/2016
-----------------------------------------------------

ALTER TABLE SICEE.SICEE_T_DATI_XML_2015 DROP COLUMN FK_PROPRIETA_EDI;

ALTER TABLE SICEE.SICEE_T_DATI_GENERALI  ADD (FK_PROPRIETA_EDI  NUMBER(3));
ALTER TABLE SICEE_T_DATI_GENERALI
       ADD  CONSTRAINT FK_SICEE_D_PROPR_EDIF_2015_01
              FOREIGN KEY (FK_PROPRIETA_EDI)
                             REFERENCES SICEE_D_PROPRIETA_EDIF_2015 ;
----------------------------------------------------------------------------------------------------------------------------------------------------


-----------------------------------------------------
-- Mail Fernanda del 07/03/2016
-----------------------------------------------------

ALTER TABLE SICEE.SICEE_T_CERTIFICATORE MODIFY(CODICE_FISCALE VARCHAR2(30 BYTE));
ALTER TABLE SICEE.SICEE_T_CERTIFICATORE  ADD (STATO_RES_ESTERO  VARCHAR2(100));
ALTER TABLE SICEE.SICEE_T_CERTIFICATORE  ADD (CITTA_ESTERA  VARCHAR2(50));
ALTER TABLE SICEE.SICEE_T_CERTIFICATORE  ADD (VIA_ESTERA  VARCHAR2(100));
ALTER TABLE SICEE.SICEE_T_CERTIFICATORE  ADD (CIVICO_ESTERO  VARCHAR2(10));
ALTER TABLE SICEE.SICEE_T_CERTIFICATORE  ADD (CAP_ESTERO  VARCHAR2(10));

ALTER TABLE SICEE.SICEE_T_CERTIFICATORE  ADD (FLG_RESIDENZA_ITALIA  VARCHAR2(1)  DEFAULT 'S');

ALTER TABLE SICEE.SICEE_T_CERTIFICATO  ADD (COD_FISC_COCERTIFICATORE  VARCHAR2(30));
ALTER TABLE SICEE.SICEE_T_CERTIFICATO MODIFY(NUM_COCERTIFICATORE VARCHAR2(100 BYTE));


ALTER TABLE  SICEE_T_DET_IMP_2015 DROP CONSTRAINT FK_SICEE_T_CERTIFICATO_31;
ALTER TABLE  SICEE_T_DET_IMP_2015 DROP CONSTRAINT FK_SICEE_D_SERV_ENER_2015_01;



CREATE TABLE SICEE_R_CERTIF_SERVENER2015 (
       ID_CERTIFICATORE     VARCHAR2(5) NOT NULL,
       PROGR_CERTIFICATO    VARCHAR2(4) NOT NULL,
       ANNO                 VARCHAR2(4) NOT NULL,
       ID_SERV_ENER         NUMBER(3) NOT NULL,
       EFFICIENZA           NUMBER(14,4)  NULL,
       EPREN                NUMBER(14,4)  NULL,
       EPNREN               NUMBER(14,4)  NULL
);


ALTER TABLE SICEE_R_CERTIF_SERVENER2015
       ADD   CONSTRAINT PK_SICEE_R_CERTIF_SERVENER2015 PRIMARY KEY (
              ID_CERTIFICATORE, PROGR_CERTIFICATO, ANNO, ID_SERV_ENER ) ;



-----------------------------------------------------
-- TRATTAMENTO DATI
-----------------------------------------------------
insert into SICEE_R_CERTIF_SERVENER2015 (ID_CERTIFICATORE,PROGR_CERTIFICATO, ANNO, ID_SERV_ENER, EFFICIENZA, EPREN, EPNREN)
SELECT SICEE_T_DET_IMP_2015.ID_CERTIFICATORE, SICEE_T_DET_IMP_2015.PROGR_CERTIFICATO, SICEE_T_DET_IMP_2015.ANNO, 
SICEE_T_DET_IMP_2015.FK_SERV_ENER, Max(SICEE_T_DET_IMP_2015.EFFICIENZA) AS EFFICIENZA, 
Sum(SICEE_T_DET_IMP_2015.EPREN) AS EPREN, Sum(SICEE_T_DET_IMP_2015.EPNREN) AS EPRNEN
FROM SICEE_T_DET_IMP_2015
GROUP BY SICEE_T_DET_IMP_2015.ID_CERTIFICATORE, SICEE_T_DET_IMP_2015.PROGR_CERTIFICATO, 
SICEE_T_DET_IMP_2015.ANNO, SICEE_T_DET_IMP_2015.FK_SERV_ENER;

commit;



ALTER TABLE SICEE.SICEE_T_DET_IMP_2015 drop column EFFICIENZA ;
ALTER TABLE SICEE.SICEE_T_DET_IMP_2015 drop column EPREN ;
ALTER TABLE SICEE.SICEE_T_DET_IMP_2015 drop column EPNREN ;

ALTER TABLE SICEE_T_DET_IMP_2015  ADD   CONSTRAINT FK_SICEE_R_CER_SERVENER2015_01
    FOREIGN KEY (ID_CERTIFICATORE, PROGR_CERTIFICATO, ANNO, FK_SERV_ENER) REFERENCES SICEE_R_CERTIF_SERVENER2015 ;



ALTER TABLE SICEE_R_CERTIF_SERVENER2015
       ADD  CONSTRAINT FK_SICEE_D_SERV_ENER_2015_01
              FOREIGN KEY (ID_SERV_ENER)
                             REFERENCES SICEE_D_SERV_ENER_2015  ;


ALTER TABLE SICEE_R_CERTIF_SERVENER2015
       ADD   CONSTRAINT FK_SICEE_T_CERTIFICATO_31
              FOREIGN KEY (ID_CERTIFICATORE, PROGR_CERTIFICATO, ANNO)
                             REFERENCES SICEE_T_CERTIFICATO ;


--- DA SENTIRE FERNANDA  -- Reineri mi ha detto di si

UPDATE SICEE_R_CERTIF_SERVENER2015 B SET (EFFICIENZA, EPREN, EPNREN) = 
( SELECT EFFICIENZA, EPREN, EPNREN FROM SICEE_T_DET_IMP_2015 A
  WHERE A.ID_CERTIFICATORE = B.ID_CERTIFICATORE
  AND A.PROGR_CERTIFICATO = B.PROGR_CERTIFICATO
  AND A.ANNO = B.ANNO);






----------------------------------------------------------------------------------------------------------------------------------------------------
CREATE TABLE SICEE_D_PROPRIETA_EDIF_2015 (
       ID_PROPRIETA_EDI     NUMBER(3) NOT NULL,
       DESCR                VARCHAR2(50) NULL
);


ALTER TABLE SICEE_D_PROPRIETA_EDIF_2015
       ADD   CONSTRAINT PK_SICEE_D_PROPRIETA_EDIF_2015 PRIMARY KEY (
              ID_PROPRIETA_EDI ) ;


CREATE TABLE SICEE_D_TIPO_RISTRUTT_2015 (
       ID_TIPO_RISTRUTTURAZ NUMBER(3) NOT NULL,
       DESCR                VARCHAR2(100) NULL
);


ALTER TABLE SICEE_D_TIPO_RISTRUTT_2015
       ADD   CONSTRAINT PK_SICEE_D_TIPO_RISTRUTT_2015 PRIMARY KEY (
              ID_TIPO_RISTRUTTURAZ) ;


CREATE TABLE SICEE_D_TIPO_VENTILAZIONE_2015 (
       ID_TIPO_VENTILAZIONE NUMBER(3) NOT NULL,
       DESCR                VARCHAR2(50) NULL
);


ALTER TABLE SICEE_D_TIPO_VENTILAZIONE_2015
       ADD   CONSTRAINT PK_SICEE_D_TIPO_VENTILAZIONE_2 PRIMARY KEY (
              ID_TIPO_VENTILAZIONE ) ;


CREATE TABLE SICEE_D_TIPOL_COSTRUTT_2015 (
       ID_TIPOL_COSTRUTT    NUMBER(3) NOT NULL,
       DESCR                VARCHAR2(100) NULL
);


ALTER TABLE SICEE_D_TIPOL_COSTRUTT_2015
       ADD   CONSTRAINT PK_SICEE_D_TIPOL_COSTRUTT_2015 PRIMARY KEY (
              ID_TIPOL_COSTRUTT ) ;


CREATE TABLE SICEE_D_TIPOL_EDILIZIA_2015 (
       ID_TIPOL_EDILIZIA    NUMBER(3) NOT NULL,
       DESCR                VARCHAR2(100) NULL
);


ALTER TABLE SICEE_D_TIPOL_EDILIZIA_2015
       ADD  CONSTRAINT PK_SICEE_D_TIPOL_EDILIZIA_2015 PRIMARY KEY (
              ID_TIPOL_EDILIZIA ) ;


CREATE TABLE SICEE_T_DATI_XML_2015 (
       ID_CERTIFICATORE     VARCHAR2(5) NOT NULL,
       PROGR_CERTIFICATO    VARCHAR2(4) NOT NULL,
       ANNO                 VARCHAR2(4) NOT NULL,
       FK_PROPRIETA_EDI     NUMBER(3) NULL,
       FK_TIPO_VENTILAZIONE NUMBER(3) NULL,
       DT_TITOLO_ABILITATIVO DATE NULL,
       FLG_SISTEMA_CONTABILIZZAZIONE CHAR(1) NULL
                                   CONSTRAINT DOM_S_N95
                                          CHECK (FLG_SISTEMA_CONTABILIZZAZIONE IN ('S','N')),
       HT                   NUMBER(14,4) NULL,
       SUP_DISP_TOT_OPACA   NUMBER(14,4) NULL,
       SUP_DISP_TOT_TRASP   NUMBER(14,4) NULL,
       TRASMITTANZA_MED_SUP_OPACHE NUMBER(14,4) NULL,
       TRASMITTANZA_MED_SUP_TRASP NUMBER(14,4) NULL,
       PORTATA_VENTILAZIONE_TOT NUMBER(14,4) NULL,
       EFFICIENZA_RECUPERO_MEDIO NUMBER(14,4) NULL
);


ALTER TABLE SICEE_T_DATI_XML_2015
       ADD   CONSTRAINT PK_SICEE_T_DATI_XML_2015 PRIMARY KEY (
              ID_CERTIFICATORE, PROGR_CERTIFICATO, ANNO ) ;


CREATE TABLE SICEE_T_DATI_XML_ED_REALE_2015 (
       ID_CERTIFICATORE     VARCHAR2(5) NOT NULL,
       PROGR_CERTIFICATO    VARCHAR2(4) NOT NULL,
       ANNO                 VARCHAR2(4) NOT NULL,
       FABB_RISC_INVOLUCRO_EXTRA_FLUS NUMBER(14,4) NULL,
       FABB_RISC_INVOLUCRO_TRASMISSIO NUMBER(14,4) NULL,
       FABB_RISC_INVOLUCRO_VENTILAZIO NUMBER(14,4) NULL,
       FABB_RISC_INVOLUCRO_APPORTI_SO NUMBER(14,4) NULL,
       FABB_RISC_INVOLUCRO_APPORTI_IN NUMBER(14,4) NULL,
       FABB_RISC_INVOLUCRO_APPORTI_LA NUMBER(14,4) NULL,
       FABB_RISC_INVOLUCRO_QHND NUMBER(14,4) NULL,
       FABB_RISC_INVOLUCRO_QLR NUMBER(14,4) NULL,
       FABB_RISC_INVOLUCRO_QHIMP NUMBER(14,4) NULL,
       FABB_RISC_IMPIANTO_ETAR NUMBER(14,4) NULL,
       FABB_RISC_IMPIANTO_ETAD NUMBER(14,4) NULL,
       FABB_RISC_IMPIANTO_ETAE NUMBER(14,4) NULL,
       FABB_RISC_IMPIANTO_ETAG NUMBER(14,4) NULL
);


ALTER TABLE SICEE_T_DATI_XML_ED_REALE_2015
       ADD   CONSTRAINT PK_SICEE_T_DATI_XML_ED_REALE_2 PRIMARY KEY (
              ID_CERTIFICATORE, PROGR_CERTIFICATO, ANNO ) ;


CREATE TABLE SICEE_T_DATI_XML_ED_RIF_2015 (
       ID_CERTIFICATORE     VARCHAR2(5) NOT NULL,
       PROGR_CERTIFICATO    VARCHAR2(4) NOT NULL,
       ANNO                 VARCHAR2(4) NOT NULL,
       QH                   NUMBER(14,4) NULL,
       QC                   NUMBER(14,4) NULL,
       EPHND                NUMBER(14,4) NULL,
       EPCND                NUMBER(14,4) NULL,
       EPH                  NUMBER(14,4) NULL,
       EPC                  NUMBER(14,4) NULL,
       EPW                  NUMBER(14,4) NULL,
       EPV                  NUMBER(14,4) NULL,
       EPL                   NUMBER(14,4) NULL,
       EPGLNR               NUMBER(14,4) NULL,
       EPGLR                NUMBER(14,4) NULL,
       EPGLTOT              NUMBER(14,4) NULL,
       ETAH                 NUMBER(14,4) NULL,
       ETAC                 NUMBER(14,4) NULL,
       ETAW                 NUMBER(14,4) NULL
);


ALTER TABLE SICEE_T_DATI_XML_ED_RIF_2015
       ADD   CONSTRAINT PK_SICEE_T_DATI_XML_ED_RIF_201 PRIMARY KEY (
              ID_CERTIFICATORE, PROGR_CERTIFICATO, ANNO ) ;


ALTER TABLE SICEE_T_DATI_XML_2015
       ADD   CONSTRAINT FK_SICEE_D_TIPO_VENT_2015_01
              FOREIGN KEY (FK_TIPO_VENTILAZIONE)
                             REFERENCES SICEE_D_TIPO_VENTILAZIONE_2015  ;


ALTER TABLE SICEE_T_DATI_XML_2015
       ADD  CONSTRAINT FK_SICEE_D_PROPR_EDIF_2015_01
              FOREIGN KEY (FK_PROPRIETA_EDI)
                             REFERENCES SICEE_D_PROPRIETA_EDIF_2015  ;


ALTER TABLE SICEE_T_DATI_XML_2015
       ADD   CONSTRAINT FK_SICEE_T_CERTIFICATO_34
              FOREIGN KEY (ID_CERTIFICATORE, PROGR_CERTIFICATO, ANNO)
                             REFERENCES SICEE_T_IMPORT_DATI_2015  ;


ALTER TABLE SICEE_T_DATI_XML_ED_REALE_2015
       ADD   CONSTRAINT FK_SICEE_T_IMP_DATI_2015_01
              FOREIGN KEY (ID_CERTIFICATORE, PROGR_CERTIFICATO, ANNO)
                             REFERENCES SICEE_T_IMPORT_DATI_2015  ;


ALTER TABLE SICEE_T_DATI_XML_ED_RIF_2015
       ADD   CONSTRAINT FK_SICEE_T_IMP_DATI_2015_02
              FOREIGN KEY (ID_CERTIFICATORE, PROGR_CERTIFICATO, ANNO)
                             REFERENCES SICEE_T_IMPORT_DATI_2015  ;



ALTER TABLE SICEE_T_DATI_GENERALI
       ADD   CONSTRAINT FK_SICEE_D_TIPOL_COSTR_2015_01
              FOREIGN KEY (FK_TIPOL_COSTRUTTIVA)
                             REFERENCES SICEE_D_TIPOL_COSTRUTT_2015  ;


ALTER TABLE SICEE_T_DATI_GENERALI
       ADD   CONSTRAINT FK_SICEE_D_TIPOL_EDIL_2015_01
              FOREIGN KEY (FK_TIPOL_EDILIZIA)
                             REFERENCES SICEE_D_TIPOL_EDILIZIA_2015 ;
                             
                             
ALTER TABLE SICEE_T_DATI_GENERALI
       ADD   CONSTRAINT FK_SICEE_D_TIPO_RISTR_2015_01
              FOREIGN KEY (FK_TIPO_RISTRUTTURAZ)
                             REFERENCES SICEE_D_TIPO_RISTRUTT_2015 ;


------------------------------------------------------------------------------------------------------------------------------------
--  AGGIUNTE DEL 17/02/2016, IN SEGUITO ALLA CALATA DI MARIUCCIA CON REINERI
-- LANCIATA IN SVILUPPO
------------------------------------------------------------------------------------------------------------------------------------
CREATE TABLE SICEE_T_IMPDATI_XML_2015 (
       ID_CERTIFICATORE     VARCHAR2(5) NOT NULL,
       PROGR_CERTIFICATO    VARCHAR2(4) NOT NULL,
       ANNO                 VARCHAR2(4) NOT NULL,
       F_XML                XMLTYPE NULL
);


ALTER TABLE SICEE_T_IMPDATI_XML_2015
       ADD   CONSTRAINT PK_SICEE_T_IMPDATI_XML_2015 PRIMARY KEY (
              ID_CERTIFICATORE, PROGR_CERTIFICATO, ANNO) ;


ALTER TABLE SICEE_T_IMPDATI_XML_2015
       ADD  CONSTRAINT FK_SICEE_T_IMP_DATI_2015_03
              FOREIGN KEY (ID_CERTIFICATORE, PROGR_CERTIFICATO, ANNO)
                             REFERENCES SICEE_T_IMPORT_DATI_2015  ;



------------------------------------------------------------------------------------------------------------------------------------
-- Script già lanciati da Reineri in sviluppo  11/03/2016
------------------------------------------------------------------------------------------------------------------------------------


SET DEFINE OFF;
Insert into SICEE.SICEE_D_TIPO_RISTRUTT_2015
   (ID_TIPO_RISTRUTTURAZ, DESCR)
 Values
   (0, 'Nuova costruzione');
Insert into SICEE.SICEE_D_TIPO_RISTRUTT_2015
   (ID_TIPO_RISTRUTTURAZ, DESCR)
 Values
   (1, 'Demolizione e ricostruzione');
Insert into SICEE.SICEE_D_TIPO_RISTRUTT_2015
   (ID_TIPO_RISTRUTTURAZ, DESCR)
 Values
   (2, 'Ampliamento e sopra elevazione');
Insert into SICEE.SICEE_D_TIPO_RISTRUTT_2015
   (ID_TIPO_RISTRUTTURAZ, DESCR)
 Values
   (3, 'Ristrutturazione importante di primo livello');
Insert into SICEE.SICEE_D_TIPO_RISTRUTT_2015
   (ID_TIPO_RISTRUTTURAZ, DESCR)
 Values
   (4, 'Ristrutturazione importante di secondo livello');
Insert into SICEE.SICEE_D_TIPO_RISTRUTT_2015
   (ID_TIPO_RISTRUTTURAZ, DESCR)
 Values
   (5, 'Riqualificazione energetica');
COMMIT;


Insert into SICEE.SICEE_D_TIPO_VENTILAZIONE_2015
   (ID_TIPO_VENTILAZIONE, DESCR)
 Values
   (0, 'naturale');
Insert into SICEE.SICEE_D_TIPO_VENTILAZIONE_2015
   (ID_TIPO_VENTILAZIONE, DESCR)
 Values
   (1, 'meccanica (solo ventilazione)');
Insert into SICEE.SICEE_D_TIPO_VENTILAZIONE_2015
   (ID_TIPO_VENTILAZIONE, DESCR)
 Values
   (2, 'meccanica (con climatizzazione)');
Insert into SICEE.SICEE_D_TIPO_VENTILAZIONE_2015
   (ID_TIPO_VENTILAZIONE, DESCR)
 Values
   (3, 'ibrida');
Insert into SICEE.SICEE_D_TIPO_VENTILAZIONE_2015
   (ID_TIPO_VENTILAZIONE, DESCR)
 Values
   (4, 'altro');
COMMIT;



------------------------------------------------------------------------------------------------------------------------------------
-- Script già lanciati da Reineri in sviluppo  23/03/2016
------------------------------------------------------------------------------------------------------------------------------------

insert into SICEE_D_TIPOL_EDILIZIA_2015 (ID_TIPOL_EDILIZIA, DESCR) values (0, 'Edificio in linea');
insert into SICEE_D_TIPOL_EDILIZIA_2015 (ID_TIPOL_EDILIZIA, DESCR) values (1, 'Edificio a torre');
insert into SICEE_D_TIPOL_EDILIZIA_2015 (ID_TIPOL_EDILIZIA, DESCR) values (2, 'Edificio a schiera');
insert into SICEE_D_TIPOL_EDILIZIA_2015 (ID_TIPOL_EDILIZIA, DESCR) values (3, 'Edificio isolata (villetta monofamiliare)');
insert into SICEE_D_TIPOL_EDILIZIA_2015 (ID_TIPOL_EDILIZIA, DESCR) values (4, 'Edificio isolata (villetta plurifamiliare)');
insert into SICEE_D_TIPOL_EDILIZIA_2015 (ID_TIPOL_EDILIZIA, DESCR) values (5, 'Edificio industriale (es.capannone)');
insert into SICEE_D_TIPOL_EDILIZIA_2015 (ID_TIPOL_EDILIZIA, DESCR) values (6, 'Edificio artigianale (es.capannone)');
insert into SICEE_D_TIPOL_EDILIZIA_2015 (ID_TIPOL_EDILIZIA, DESCR) values (7, 'Edificio commerciale (es.capannone)');
insert into SICEE_D_TIPOL_EDILIZIA_2015 (ID_TIPOL_EDILIZIA, DESCR) values (8, 'Altro'); 
COMMIT;