/*******************************************************************************
 * SPDX-License-Identifier: EUPL-1.2
 * Copyright Regione Piemonte - 2020
 *******************************************************************************/
GRANT ALTER, SELECT ON SEQ_SICEE_T_CERTIFICATORE TO SICEE_RW;
GRANT ALTER, SELECT ON SEQ_SICEE_T_AZIENDA TO SICEE_RW;
GRANT ALTER, SELECT ON SEQ_SICEE_T_TRANSAZIONE TO SICEE_RW;
GRANT SELECT,UPDATE,DELETE,INSERT ON SICEE_D_TIPO_IMPIANTO TO SICEE_RW;
GRANT SELECT,UPDATE,DELETE,INSERT ON SICEE_D_TIPO_PAGAMENTO TO SICEE_RW;
GRANT SELECT,UPDATE,DELETE,INSERT ON SICEE_D_TITOLO TO SICEE_RW;
GRANT SELECT,UPDATE,DELETE,INSERT ON SICEE_R_DEST_CLASSE TO SICEE_RW;
GRANT SELECT,UPDATE,DELETE,INSERT ON SICEE_T_ALTRE_INFO TO SICEE_RW;
GRANT SELECT,UPDATE,DELETE,INSERT ON SICEE_T_AZIENDA TO SICEE_RW;
GRANT SELECT,UPDATE,DELETE,INSERT ON SICEE_T_CERTIFICATO TO SICEE_RW;
GRANT SELECT,UPDATE,DELETE,INSERT ON SICEE_T_CERTIFICATORE TO SICEE_RW;
GRANT SELECT,UPDATE,DELETE,INSERT ON SICEE_T_CLASSE_ENERGETICA TO SICEE_RW;
GRANT SELECT,UPDATE,DELETE,INSERT ON SICEE_T_CONSUMI_EDIFICIO TO SICEE_RW;
GRANT SELECT,UPDATE,DELETE,INSERT ON SICEE_T_DATI_GENERALI TO SICEE_RW;
GRANT SELECT,UPDATE,DELETE,INSERT ON SICEE_T_ENERGIA_SOPR_INGR TO SICEE_RW;
GRANT SELECT,UPDATE,DELETE,INSERT ON SICEE_T_FABBISOGNO TO SICEE_RW;
GRANT SELECT,UPDATE,DELETE,INSERT ON SICEE_T_IMP_RISCALDAMENTO_ACS TO SICEE_RW;
GRANT SELECT,UPDATE,DELETE,INSERT ON SICEE_T_LIMITEQH_PIEMONTE TO SICEE_RW;
GRANT SELECT,UPDATE,DELETE,INSERT ON SICEE_T_RACCOMANDAZIONI TO SICEE_RW;
GRANT SELECT,UPDATE,DELETE,INSERT ON SICEE_T_RISPETTO_NORMATIVE TO SICEE_RW;
GRANT SELECT,UPDATE,DELETE,INSERT ON SICEE_T_RUOLI_EDIFICIO TO SICEE_RW;
GRANT SELECT,UPDATE,DELETE,INSERT ON SICEE_T_TRANSAZIONE_ACE TO SICEE_RW;
GRANT SELECT,UPDATE,DELETE,INSERT ON SICEE_T_TRANSAZIONE_REGISTRAZ TO SICEE_RW;
GRANT SELECT,UPDATE,DELETE,INSERT ON SICEE_W_PREZZI TO SICEE_RW;
GRANT SELECT,UPDATE,DELETE,INSERT ON SICEE_D_GRADI_GIORNO TO SICEE_RW;
GRANT SELECT,UPDATE,DELETE,INSERT ON SICEE_D_CLASSE_EFFICIENZA TO SICEE_RW;
GRANT SELECT,UPDATE,DELETE,INSERT ON SICEE_D_CLASSE_ENERGETICA TO SICEE_RW;
GRANT SELECT,UPDATE,DELETE,INSERT ON SICEE_D_COMBUSTIBILE TO SICEE_RW;
GRANT SELECT,UPDATE,DELETE,INSERT ON SICEE_D_DATI_INGRESSO TO SICEE_RW;
GRANT SELECT,UPDATE,DELETE,INSERT ON SICEE_D_DEST_USO TO SICEE_RW;
GRANT SELECT,UPDATE,DELETE,INSERT ON SICEE_D_DICHIARAZIONE TO SICEE_RW;
GRANT SELECT,UPDATE,DELETE,INSERT ON SICEE_D_MOTIVO_RILASCIO TO SICEE_RW;
GRANT SELECT,UPDATE,DELETE,INSERT ON SICEE_D_NORMATIVA TO SICEE_RW;
GRANT SELECT,UPDATE,DELETE,INSERT ON SICEE_D_PRIORITA TO SICEE_RW;
GRANT SELECT,UPDATE,DELETE,INSERT ON SICEE_D_QUALITA_INVOLUCRO TO SICEE_RW;
GRANT SELECT,UPDATE,DELETE,INSERT ON SICEE_D_RUOLO TO SICEE_RW;
GRANT SELECT,UPDATE,DELETE,INSERT ON SICEE_D_SISTEMA_RACC TO SICEE_RW;
GRANT SELECT,UPDATE,DELETE,INSERT ON SICEE_D_STATO_CERT TO SICEE_RW;
GRANT SELECT,UPDATE,DELETE,INSERT ON SICEE_W_CERTIFICATORE TO SICEE_RW;
