/*******************************************************************************
 * SPDX-License-Identifier: EUPL-1.2
 * Copyright Regione Piemonte - 2020
 *******************************************************************************/

ALTER TABLE SICEE_T_PARAMETRI
       ADD  ( CONSTRAINT PK_SICEE_T_PARAMETRI PRIMARY KEY (CODICE)
       USING INDEX
              TABLESPACE SICEE_SMALL_IDX ) ;
              
              
ALTER TABLE SICEE_L_LOG_BATCH ADD STATO VARCHAR2(2);


CREATE TABLE SICEE_L_ANOMALIE_BATCH (
       ID_ANOMALIA          NUMBER NOT NULL,
       FK_LOG_BATCH         NUMBER NOT NULL,
       NOME_FILE            VARCHAR2(50) NULL,
       ANOMALIA             VARCHAR2(200) NULL
)
       TABLESPACE SICEE_SMALL_TBL
;


ALTER TABLE SICEE_L_ANOMALIE_BATCH
       ADD  ( CONSTRAINT PK_SICEE_L_ANOMALIE_BATCH PRIMARY KEY (
              ID_ANOMALIA)
       USING INDEX
              TABLESPACE SICEE_SMALL_IDX ) ;


ALTER TABLE SICEE_L_ANOMALIE_BATCH
       ADD  ( CONSTRAINT FK_SICEE_L_LOG_BATCH_01
              FOREIGN KEY (FK_LOG_BATCH)
                             REFERENCES SICEE_L_LOG_BATCH ) ;              



ALTER TABLE SICEE_T_CERTIFICATO ADD FK_MOTIVO_SOST NUMBER(3);

ALTER TABLE SICEE_T_CERTIFICATO ADD DT_SOSTITUZIONE DATE; 

ALTER TABLE SICEE_T_CERTIFICATO ADD NOTE_SOSTITUZIONE VARCHAR2(2000);

ALTER TABLE SICEE_T_CERTIFICATO ADD DT_FOTO DATE;

CREATE TABLE SICEE_D_PARAMETRI_SOST (
       ID_PARAMETRO_SOST    NUMBER(4) NOT NULL,
       NOME_CAMPO           VARCHAR2(100) NULL,
       LABEL                VARCHAR2(100) NULL
)
       TABLESPACE SICEE_SMALL_TBL
;


ALTER TABLE SICEE_D_PARAMETRI_SOST
       ADD  ( CONSTRAINT PK_SICEE_D_PARAMETRI_SOST PRIMARY KEY (
              ID_PARAMETRO_SOST)
       USING INDEX
              TABLESPACE SICEE_SMALL_IDX ) ;
              
              
CREATE TABLE SICEE_D_MOTIVO_SOST (
       ID_MOTIVO_SOST       NUMBER(3) NOT NULL,
       DESCR                VARCHAR2(50) NULL,
       MIN                  NUMBER(3) NULL,
       MAX                  NUMBER(3) NULL
)
       TABLESPACE SICEE_SMALL_TBL
;


ALTER TABLE SICEE_D_MOTIVO_SOST
       ADD  ( CONSTRAINT PK_SICEE_D_MOTIVO_SOST PRIMARY KEY (
              ID_MOTIVO_SOST)
       USING INDEX
              TABLESPACE SICEE_SMALL_IDX ) ;


CREATE TABLE SICEE_R_MOTIVO_PARAM (
       ID_PARAMETRO_SOST    NUMBER(4) NOT NULL,
       ID_MOTIVO_SOST       NUMBER(3) NOT NULL
)
       TABLESPACE SICEE_SMALL_TBL
;


ALTER TABLE SICEE_R_MOTIVO_PARAM
       ADD  ( CONSTRAINT PK_SICEE_R_MOTIVO_PARAM PRIMARY KEY (
              ID_PARAMETRO_SOST, ID_MOTIVO_SOST)
       USING INDEX
              TABLESPACE SICEE_SMALL_IDX ) ;
              
              
CREATE TABLE SICEE_T_DICHIARAZIONE_SOST (
       ID_DICHIARAZIONE_SOST NUMBER(5) NOT NULL,
       FK_SOSTITUZIONE      NUMBER(9) NOT NULL,
       FK_PROGR_SOSTITUZIONE NUMBER(9) NOT NULL,
       FK_PARAMETRO_SOST    NUMBER(4) NOT NULL,
       VALORE_PARAMETRO_SOST CHAR(18) NULL
)
       TABLESPACE SICEE_SMALL_TBL
;


ALTER TABLE SICEE_T_DICHIARAZIONE_SOST
       ADD  ( CONSTRAINT PK_SICEE_T_DICHIARAZIONE_SOST PRIMARY KEY (
              ID_DICHIARAZIONE_SOST)
       USING INDEX
              TABLESPACE SICEE_SMALL_IDX ) ;
              
              
              
CREATE TABLE SICEE_T_SOSTITUZIONE (
       ID_SOSTITUZIONE      NUMBER(9) NOT NULL,
       PROGR_SOSTITUZIONE   NUMBER(9) NOT NULL,
       ID_CERTIFICATORE_OLD VARCHAR2(5) NOT NULL,
       PROGR_CERTIFICATO_OLD VARCHAR2(4) NOT NULL,
       ANNO_OLD             VARCHAR2(4) NOT NULL,
       ID_CERTIFICATORE_NEW VARCHAR2(5) NOT NULL,
       PROGR_CERTIFICATO_NEW VARCHAR2(4) NOT NULL,
       ANNO_NEW             VARCHAR2(4) NOT NULL,
       FLG_INVIO_MAIL       CHAR(1) NULL
                                   CONSTRAINT CHK_INVIO
                                          CHECK (FLG_INVIO_MAIL IN ('S','N')),
       EMAIL                VARCHAR2(70) NULL
)
       TABLESPACE SICEE_SMALL_TBL
;



ALTER TABLE SICEE_T_SOSTITUZIONE
       ADD  ( CONSTRAINT PK_SICEE_T_SOSTITUZIONE PRIMARY KEY (
              ID_SOSTITUZIONE, PROGR_SOSTITUZIONE)
       USING INDEX
              TABLESPACE SICEE_SMALL_IDX ) ;                                          



ALTER TABLE SICEE_R_MOTIVO_PARAM
       ADD  ( CONSTRAINT FK_SICEE_D_MOTIVOSOST_02
              FOREIGN KEY (ID_MOTIVO_SOST)
                             REFERENCES SICEE_D_MOTIVO_SOST ) ;


ALTER TABLE SICEE_R_MOTIVO_PARAM
       ADD  ( CONSTRAINT FK_SICEE_D_PARAMETRI_01
              FOREIGN KEY (ID_PARAMETRO_SOST)
                             REFERENCES SICEE_D_PARAMETRI_SOST ) ;

ALTER TABLE SICEE_T_CERTIFICATO
       ADD  ( CONSTRAINT FK_SICEE_D_MOTIVOSOST_01
              FOREIGN KEY (FK_MOTIVO_SOST)
                             REFERENCES SICEE_D_MOTIVO_SOST ) ;

ALTER TABLE SICEE_T_DICHIARAZIONE_SOST
       ADD  ( CONSTRAINT FK_SICEE_D_PARAMETRI_02
              FOREIGN KEY (FK_PARAMETRO_SOST)
                             REFERENCES SICEE_D_PARAMETRI_SOST ) ;


ALTER TABLE SICEE_T_DICHIARAZIONE_SOST
       ADD  ( CONSTRAINT FK_SICEE_T_SOSTITUZIONE_01
              FOREIGN KEY (FK_SOSTITUZIONE, FK_PROGR_SOSTITUZIONE)
                             REFERENCES SICEE_T_SOSTITUZIONE ) ;

ALTER TABLE SICEE_T_SOSTITUZIONE
       ADD  ( CONSTRAINT FK_SICEE_T_CERTIFICATO_18
              FOREIGN KEY (ID_CERTIFICATORE_NEW, 
              PROGR_CERTIFICATO_NEW, ANNO_NEW)
                             REFERENCES SICEE_T_CERTIFICATO ) ;


ALTER TABLE SICEE_T_SOSTITUZIONE
       ADD  ( CONSTRAINT FK_SICEE_T_CERTIFICATO_19
              FOREIGN KEY (ID_CERTIFICATORE_OLD, 
              PROGR_CERTIFICATO_OLD, ANNO_OLD)
                             REFERENCES SICEE_T_CERTIFICATO ) ;
                             
DROP TABLE SICEE_T_EXPORT_BO;
                             
CREATE TABLE SICEE_T_EXPORT_BO (
       ANNO                 VARCHAR2(4) NOT NULL,
       ID_CERTIFICATORE     VARCHAR2(5) NOT NULL,
       PROGR_CERTIFICATO    VARCHAR2(4) NOT NULL,
       FK_STATO             NUMBER(3) NULL,
       DT_INIZIO            DATE NULL,
       DT_UPLOAD            DATE NULL,
       DESC_PROV            VARCHAR2(50) NULL,
       ID_PROV              VARCHAR2(6) NULL,
       DESC_COMUNE          VARCHAR2(50) NULL,
       ID_COMUNE            VARCHAR2(6) NULL,
       DESC_INDIRIZZO       VARCHAR2(160) NULL,
       NUM_CIVICO           VARCHAR2(10) NULL,
       SEZIONE              VARCHAR2(5) NULL,
       FOGLIO               VARCHAR2(5) NULL,
       PARTICELLA           VARCHAR2(9) NULL,
       SUBALTERNO           VARCHAR2(4) NULL,
       GRADI_GIORNO         NUMBER(6) NULL,
       PIANO                NUMBER(3) NULL,
       NUM_PIANI_COMPLESSIVI NUMBER(3) NULL,
       FK_DEST_USO          NUMBER(3) NULL,
       FK_CARATT_EDIFICIO          NUMBER(6) NULL,
       DESC_TIPO_EDIFICIO   VARCHAR2(100) NULL,
       ANNO_COSTRUZIONE     NUMBER(4) NULL,
       ANNO_ULT_RIST        NUMBER(4) NULL,
       VOL_LORDO_RISCALDATO NUMBER(14,4) NULL,
       SUP_DISPERDENTE_TOT  NUMBER(14,4) NULL,
       SU                   NUMBER(14,4) NULL,
       V_SU                 NUMBER(14,4) NULL,
       FATTORE_FORMA        NUMBER(14,4) NULL,
       TRASM_OPACHE         NUMBER(14,4) NULL,
       TRASM_TRASP          NUMBER(14,4) NULL,
       FK_TIPO_IMPIANTO     NUMBER(3) NULL,
       FK_COMBUSTIBILE_RISC NUMBER(3) NULL,
       FK_COMBUSTIBILE_ACS  NUMBER(3) NULL,
       FK_CLASSE            NUMBER(3) NULL,
       FK_CLASSE_192_05     NUMBER(3) NULL,
       DOM_RISC_QH          NUMBER(14,4) NULL,
       DOM_RISC_QHTO        NUMBER(14,4) NULL,
       DOM_ACS_QHW          NUMBER(14,4) NULL,
       DOM_ACS_QHWTO        NUMBER(14,4) NULL,
       FLG_FABB_ACS         CHAR(1) NULL,
       EN_ACS_RINNO         NUMBER(14,4) NULL,
       DOM_ACS_QHW_SU       NUMBER(14,4) NULL,
       REND_IMP_ETAG        NUMBER(14,4) NULL,
       REND_ACS_ETAGACS     NUMBER(17,5) NULL,
       VALORE_PREST_PDC     NUMBER(14,4) NULL,
       IND_RISC_EPI         NUMBER(14,4) NULL,
       IND_RISC_EPITO       NUMBER(14,4) NULL,
       FLG_FABB_MAX_INDICE  CHAR(1) NULL,
       FABB_ACS             NUMBER(14,4) NULL,
       IND_GLOB_EPLORDO     NUMBER(14,4) NULL,
       IND_GLOB_EPLORDO_TO  NUMBER(14,4) NULL,
       FK_MOTIVO            NUMBER(3) NULL,
       METODOLOGIA_CALCOLO  VARCHAR2(100) NULL,
       SW_UTILIZZATO        VARCHAR2(100) NULL,
       PRESTAZIONE_ENE      NUMBER(14,4) NULL,
       NUM_APPARTAMENTI     NUMBER(3) NULL,
       UI_SERVITE           VARCHAR2(20) NULL,
       POT_RISCALDAMENTO    NUMBER(14,4) NULL,
       FK_CLASSE_EFF_RISC   NUMBER(3) NULL,
       GEN_ANNO_RISC        NUMBER(4) NULL,
       FLG_CONT_RIP         CHAR(1) NULL,
       REND_GENER           NUMBER(14,4) NULL,
       REND_REGOL           NUMBER(14,4) NULL,
       REND_EMISS           NUMBER(14,4) NULL,
       REND_DISTRIB         NUMBER(14,4) NULL
)
       TABLESPACE SICEE_SMALL_TBL
;


GRANT SELECT,UPDATE,DELETE,INSERT ON SICEE_T_EXPORT_BO TO SICEE_RW;


ALTER TABLE SICEE_T_EXPORT_BO
       ADD  ( CONSTRAINT PK_SICEE_T_EXPORT_BO PRIMARY KEY (ANNO, 
              ID_CERTIFICATORE, PROGR_CERTIFICATO)
       USING INDEX
              TABLESPACE SICEE_SMALL_IDX ) ;


ALTER TABLE SICEE_T_EXPORT_BO
       ADD  ( CONSTRAINT FK_SICEE_T_CERTIFICATO_17
              FOREIGN KEY (ID_CERTIFICATORE, PROGR_CERTIFICATO, ANNO)
                             REFERENCES SICEE_T_CERTIFICATO ) ;
                             
                             
                             
                             


CREATE TABLE SICEE_D_TIPO_EDIFICIO (
       ID_TIPO_EDIFICIO     NUMBER(3) NOT NULL,
       FK_TIPO_IMPIANTO     NUMBER(3) NOT NULL,
       DESCR                VARCHAR2(100) NULL
)
       TABLESPACE SICEE_SMALL_TBL
;


ALTER TABLE SICEE_D_TIPO_EDIFICIO
       ADD  ( CONSTRAINT PK_SICEE_D_TIPO_EDIFICIO PRIMARY KEY (
              ID_TIPO_EDIFICIO)
       USING INDEX
              TABLESPACE SICEE_SMALL_IDX ) ;


ALTER TABLE SICEE_D_EDIFICIO ADD FK_TIPO_EDIFICIO NUMBER(3);


ALTER TABLE SICEE_D_EDIFICIO
       ADD  ( CONSTRAINT FK_SICEE_D_TIPOEDI_01
              FOREIGN KEY (FK_TIPO_EDIFICIO)
                             REFERENCES SICEE_D_TIPO_EDIFICIO ) ;


ALTER TABLE SICEE_D_TIPO_EDIFICIO
       ADD  ( CONSTRAINT FK_SICEE_D_TIPO_IMP_02
              FOREIGN KEY (FK_TIPO_IMPIANTO)
                             REFERENCES SICEE_D_TIPO_IMPIANTO ) ;



                                           
RENAME SICEE_D_EDIFICIO TO SICEE_D_CARATT_EDIFICIO;

ALTER TABLE SICEE_D_CARATT_EDIFICIO RENAME COLUMN ID_EDIFICIO TO ID_CARATT_EDIFICIO;

ALTER TABLE SICEE_T_DATI_GENERALI RENAME COLUMN FK_EDIFICIO TO FK_CARATT_EDIFICIO;

ALTER TABLE SICEE_T_DATI_GENERALI DROP CONSTRAINT FK_SICEE_D_EDIFICIO_01;

ALTER TABLE SICEE_T_DATI_GENERALI ADD  ( CONSTRAINT FK_SICEE_D_CARATT_EDIFICIO_01
              FOREIGN KEY (FK_CARATT_EDIFICIO)
                             REFERENCES SICEE_D_CARATT_EDIFICIO ) ;              

ALTER TABLE SICEE_D_CARATT_EDIFICIO RENAME CONSTRAINT PK_SICEE_D_EDIFICIO TO PK_SICEE_D_CARATT_EDIFICIO;

ALTER TABLE SICEE_T_CERTIFICATORE ADD FLG_CANC_ELENCO CHAR(1);

ALTER TABLE SICEE_T_HD_ACE_FIRMATI ADD FLG_RIPRISTINO_DATA VARCHAR2(1);




