/*******************************************************************************
 * SPDX-License-Identifier: EUPL-1.2
 * Copyright Regione Piemonte - 2020
 *******************************************************************************/

GRANT SELECT,UPDATE,DELETE,INSERT ON SICEE_T_PARAMETRI TO SICEE_RW;

GRANT SELECT,UPDATE,DELETE,INSERT ON SICEE_D_TIPO_DOCUMENTO TO SICEE_RW;
GRANT SELECT,UPDATE,DELETE,INSERT ON SICEE_T_DOCUMENTO TO SICEE_RW;

GRANT SELECT,UPDATE,DELETE,INSERT ON SICEE_R_NOTAIO_ACE TO SICEE_RW;
GRANT SELECT,UPDATE,DELETE,INSERT ON SICEE_T_NOTAIO TO SICEE_RW;

GRANT ALTER, SELECT ON SEQ_SICEE_T_DOCUMENTO TO SICEE_RW;
GRANT ALTER, SELECT ON SEQ_SICEE_R_NOTAIO_ACE TO SICEE_RW;


