/*******************************************************************************
 * SPDX-License-Identifier: EUPL-1.2
 * Copyright Regione Piemonte - 2020
 *******************************************************************************/

GRANT SELECT,UPDATE,DELETE,INSERT ON SICEE_T_DATICATAST_SEC TO SICEE_RW;
GRANT ALTER,SELECT ON SEQ_SICEE_T_DATICATAST_SEC TO SICEE_RW;

GRANT SELECT,UPDATE,DELETE,INSERT ON SICEE_T_DATI_BATCH TO SICEE_RW;
GRANT ALTER,SELECT ON SEQ_SICEE_T_DATI_BATCH TO SICEE_RW;

GRANT SELECT,UPDATE,DELETE,INSERT ON SICEE_L_LOG_BATCH TO SICEE_RW;
GRANT ALTER,SELECT ON SEQ_SICEE_L_LOG_BATCH TO SICEE_RW;


GRANT SELECT,UPDATE,DELETE,INSERT ON SICEE_T_EXPORT_BO TO SICEE_RW;
GRANT SELECT,UPDATE,DELETE,INSERT ON SICEE_D_EDIFICIO TO SICEE_RW;


