/*******************************************************************************
 * SPDX-License-Identifier: EUPL-1.2
 * Copyright Regione Piemonte - 2020
 *******************************************************************************/
ALTER TABLE SICEE.SICEE_T_ENTEFORM_SL_2015 MODIFY(SITO_WEB VARCHAR2(100 BYTE));
ALTER TABLE SICEE.SICEE_T_ENTEFORM_2015 MODIFY(SITO_WEB VARCHAR2(100 BYTE));
ALTER TABLE SICEE.SICEE_T_CERTIFICATO MODIFY(NOME_COCERTIFICATORE VARCHAR2(50 BYTE));
ALTER TABLE SICEE.SICEE_T_CERTIFICATORE MODIFY(NOME VARCHAR2(50 BYTE));

ALTER TABLE SICEE.SICEE_T_CERTIFICATORE  ADD (FK_BLOCCO_CERTIFICATORE NUMBER(3));
ALTER TABLE SICEE.SICEE_T_CERTIFICATORE  ADD (DATA_BLOCCO_CERTIFICATORE  DATE);

ALTER TABLE SICEE.SICEE_T_CERTIFICATORE ADD (NOTE_BLOCCO_CERTIFICATORE  VARCHAR2(1000));



CREATE TABLE SICEE_D_BLOCCO_CERTIFICATORE (
       ID_BLOCCO_CERTIFICATORE NUMBER(3) NOT NULL,
       FLG_BLOCCO           NUMBER(1) NULL,
       DESCR                VARCHAR2(100) NULL
);

ALTER TABLE SICEE_D_BLOCCO_CERTIFICATORE
       ADD CONSTRAINT PK_SICEE_D_BLOCCO_CERTIFICAT PRIMARY KEY (
              ID_BLOCCO_CERTIFICATORE)  ;

ALTER TABLE SICEE_T_CERTIFICATORE ADD  CONSTRAINT FK_SICEE_D_BLOCCO_CERT_01
              FOREIGN KEY (FK_BLOCCO_CERTIFICATORE)
                             REFERENCES SICEE_D_BLOCCO_CERTIFICATORE  ;


GRANT DELETE, INSERT, SELECT, UPDATE ON SICEE_D_BLOCCO_CERTIFICATORE TO SICEE_RW;   