/*******************************************************************************
 * SPDX-License-Identifier: EUPL-1.2
 * Copyright Regione Piemonte - 2020
 *******************************************************************************/

GRANT SELECT,UPDATE,DELETE,INSERT ON SICEE_D_TIPO_ISTRUZIONE TO SICEE_RW;
GRANT SELECT,UPDATE,DELETE,INSERT ON SICEE_D_ISTRUZIONE TO SICEE_RW;
GRANT SELECT,UPDATE,DELETE,INSERT ON SICEE_T_ESAME_DPR75 TO SICEE_RW;


GRANT SELECT,UPDATE,DELETE,INSERT ON SICEE_T_VERIFY_REPORT_OLD TO SICEE_RW;
GRANT SELECT,UPDATE,DELETE,INSERT ON SICEE_T_DATI_FIRMA_OLD TO SICEE_RW;


GRANT ALTER,SELECT ON SEQ_SICEE_T_ESAME_DPR75 TO SICEE_RW;