/*******************************************************************************
 * SPDX-License-Identifier: EUPL-1.2
 * Copyright Regione Piemonte - 2020
 *******************************************************************************/
CREATE TABLE SICEE_W_CERTIFICATORE
(
  ID_CERTIFICATORE   NUMBER(5)                  NOT NULL,
  PROGR_CERTIFICATO  NUMBER(5),
  ANNO               VARCHAR2(4)           NOT NULL
)
TABLESPACE SICEE_SMALL_TBL
;

ALTER TABLE SICEE_W_CERTIFICATORE 
ADD ( CONSTRAINT PK_SICEE_W_CERTIFICATORE PRIMARY KEY (ID_CERTIFICATORE, ANNO) 
USING INDEX   TABLESPACE SICEE_SMALL_IDX)
;




CREATE TABLE SICEE_D_CLASSE_EFFICIENZA (
       ID_CLASSE_EFF        NUMBER(3) NOT NULL,
       DESCR                VARCHAR2(20) NULL
)
       TABLESPACE SICEE_SMALL_TBL
;


ALTER TABLE SICEE_D_CLASSE_EFFICIENZA
       ADD  ( CONSTRAINT PK_SICEE_D_CLASSE_EFFICIENZA PRIMARY KEY (
              ID_CLASSE_EFF)
       USING INDEX
              TABLESPACE SICEE_SMALL_IDX ) ;


CREATE TABLE SICEE_D_CLASSE_ENERGETICA (
       ID_CLASSE            NUMBER(3) NOT NULL,
       DESCR                VARCHAR2(10) NULL,
       FLG_NAZIONALE_19205  CHAR(1) NULL
)
       TABLESPACE SICEE_SMALL_TBL
;


ALTER TABLE SICEE_D_CLASSE_ENERGETICA
       ADD  ( CONSTRAINT PK_SICEE_D_CLASSE_ENERGETICA PRIMARY KEY (
              ID_CLASSE)
       USING INDEX
              TABLESPACE SICEE_SMALL_IDX ) ;


CREATE TABLE SICEE_D_COMBUSTIBILE (
       ID_COMBUSTIBILE      NUMBER(3) NOT NULL,
       DESCR                VARCHAR2(50) NULL
)
       TABLESPACE SICEE_SMALL_TBL
;


ALTER TABLE SICEE_D_COMBUSTIBILE
       ADD  ( CONSTRAINT PK_SICEE_D_COMBUSTIBILE PRIMARY KEY (
              ID_COMBUSTIBILE)
       USING INDEX
              TABLESPACE SICEE_SMALL_IDX ) ;


CREATE TABLE SICEE_D_DATI_INGRESSO (
       ID_DATI              NUMBER(3) NOT NULL,
       DESCR                VARCHAR2(50) NULL
)
       TABLESPACE SICEE_SMALL_TBL
;


ALTER TABLE SICEE_D_DATI_INGRESSO
       ADD  ( CONSTRAINT PK_SICEE_D_DATI_INGRESSO PRIMARY KEY (
              ID_DATI)
       USING INDEX
              TABLESPACE SICEE_SMALL_IDX ) ;


CREATE TABLE SICEE_D_DEST_USO (
       ID_DEST_USO          NUMBER(3) NOT NULL,
       SIGLA                VARCHAR2(10) NULL,
       DESCR                VARCHAR2(1000) NULL
)
       TABLESPACE SICEE_SMALL_TBL
;


ALTER TABLE SICEE_D_DEST_USO
       ADD  ( CONSTRAINT PK_SICEE_D_DEST_USO PRIMARY KEY (ID_DEST_USO)
       USING INDEX
              TABLESPACE SICEE_SMALL_IDX ) ;


CREATE TABLE SICEE_D_DICHIARAZIONE (
       ID_DICHIARAZIONE     NUMBER(3) NOT NULL,
       DESCR                VARCHAR2(1000) NULL
)
       TABLESPACE SICEE_SMALL_TBL
;


ALTER TABLE SICEE_D_DICHIARAZIONE
       ADD  ( CONSTRAINT PK_SICEE_D_DICHIARAZIONE PRIMARY KEY (
              ID_DICHIARAZIONE)
       USING INDEX
              TABLESPACE SICEE_SMALL_IDX ) ;


CREATE TABLE SICEE_D_GRADI_GIORNO (
       COMUNE               VARCHAR2(50) NOT NULL,
       ID_COMUNE            NUMBER(6) NOT NULL,
       ZONA_CLIMATICA       CHAR(1) NULL,
       GRADI_GIORNO         NUMBER(6) NULL
)
       TABLESPACE SICEE_SMALL_TBL
;


ALTER TABLE SICEE_D_GRADI_GIORNO
       ADD  ( CONSTRAINT PK_SICEE_D_GRADI_GIORNO PRIMARY KEY (
              ID_COMUNE)
       USING INDEX
              TABLESPACE SICEE_SMALL_IDX ) ;


CREATE TABLE SICEE_D_MOTIVO_RILASCIO (
       ID_MOTIVO            NUMBER(3) NOT NULL,
       DESCR                VARCHAR2(100) NULL
)
       TABLESPACE SICEE_SMALL_TBL
;


ALTER TABLE SICEE_D_MOTIVO_RILASCIO
       ADD  ( CONSTRAINT PK_SICEE_D_MOTIVO_RILASCIO PRIMARY KEY (
              ID_MOTIVO)
       USING INDEX
              TABLESPACE SICEE_SMALL_IDX ) ;


CREATE TABLE SICEE_D_NORMATIVA (
       ID_NORMA             NUMBER(3) NOT NULL,
       DESCR                VARCHAR2(100) NOT NULL,
       DT_INIZIO            DATE NULL,
       DT_FINE              DATE NULL
)
       TABLESPACE SICEE_SMALL_TBL
;


ALTER TABLE SICEE_D_NORMATIVA
       ADD  ( CONSTRAINT PK_SICEE_D_NORMATIVA PRIMARY KEY (ID_NORMA)
       USING INDEX
              TABLESPACE SICEE_SMALL_IDX ) ;


CREATE TABLE SICEE_D_PRIORITA (
       PRIORITA             VARCHAR2(20) NOT NULL
)
       TABLESPACE SICEE_SMALL_TBL
;


ALTER TABLE SICEE_D_PRIORITA
       ADD  ( CONSTRAINT PK_SICEE_D_PRIORITA PRIMARY KEY (PRIORITA)
       USING INDEX
              TABLESPACE SICEE_SMALL_IDX ) ;


CREATE TABLE SICEE_D_QUALITA_INVOLUCRO (
       ID_QUALITA           NUMBER(3) NOT NULL,
       DESCR                VARCHAR2(10) NULL
)
       TABLESPACE SICEE_SMALL_TBL
;


ALTER TABLE SICEE_D_QUALITA_INVOLUCRO
       ADD  ( CONSTRAINT PK_SICEE_D_QUALITA_INVOLUCRO PRIMARY KEY (
              ID_QUALITA)
       USING INDEX
              TABLESPACE SICEE_SMALL_IDX ) ;


CREATE TABLE SICEE_D_RUOLO (
       ID_TIPO_RUOLO        NUMBER(3) NOT NULL,
       DESCR                VARCHAR2(50) NULL
)
       TABLESPACE SICEE_SMALL_TBL
;


ALTER TABLE SICEE_D_RUOLO
       ADD  ( CONSTRAINT PK_SICEE_D_RUOLO PRIMARY KEY (ID_TIPO_RUOLO)
       USING INDEX
              TABLESPACE SICEE_SMALL_IDX ) ;


CREATE TABLE SICEE_D_SISTEMA_RACC (
       SISTEMA              VARCHAR2(20) NOT NULL
)
       TABLESPACE SICEE_SMALL_TBL
;


ALTER TABLE SICEE_D_SISTEMA_RACC
       ADD  ( CONSTRAINT PK_SICEE_D_SISTEMA_RACC PRIMARY KEY (SISTEMA)
       USING INDEX
              TABLESPACE SICEE_SMALL_IDX ) ;


CREATE TABLE SICEE_D_STATO_CERT (
       ID_STATO             NUMBER(3) NOT NULL,
       DESCR                VARCHAR2(50) NULL
);


ALTER TABLE SICEE_D_STATO_CERT
       ADD  ( CONSTRAINT PK_SICEE_D_STATO_CERT PRIMARY KEY (ID_STATO)
       USING INDEX
              TABLESPACE SICEE_SMALL_IDX ) ;


CREATE TABLE SICEE_D_TIPO_DISTRIB (
       ID_TIPO_DISTRIB      NUMBER(3) NOT NULL,
       DESCR                VARCHAR2(20) NULL
)
       TABLESPACE SICEE_SMALL_TBL
;


ALTER TABLE SICEE_D_TIPO_DISTRIB
       ADD  ( CONSTRAINT PK_SICEE_D_TIPO_DISTRIB PRIMARY KEY (
              ID_TIPO_DISTRIB)
       USING INDEX
              TABLESPACE SICEE_SMALL_IDX ) ;


CREATE TABLE SICEE_D_TIPO_EDIFICIO (
       ID_TIPO_EDIFICIO     NUMBER(3) NOT NULL,
       DESCR                VARCHAR2(30) NOT NULL
)
       TABLESPACE SICEE_SMALL_TBL
;


ALTER TABLE SICEE_D_TIPO_EDIFICIO
       ADD  ( CONSTRAINT PK_SICEE_D_TIPO_EDIFICIO PRIMARY KEY (
              ID_TIPO_EDIFICIO)
       USING INDEX
              TABLESPACE SICEE_SMALL_IDX ) ;


CREATE TABLE SICEE_D_TIPO_EROGAZIONE (
       ID_TIPO_EROG         NUMBER(3) NOT NULL,
       DESCR                VARCHAR2(50) NULL
)
       TABLESPACE SICEE_SMALL_TBL
;


ALTER TABLE SICEE_D_TIPO_EROGAZIONE
       ADD  ( CONSTRAINT PK_SICEE_D_TIPO_EROGAZIONE PRIMARY KEY (
              ID_TIPO_EROG)
       USING INDEX
              TABLESPACE SICEE_SMALL_IDX ) ;


CREATE TABLE SICEE_D_TIPO_IMPIANTO (
       ID_TIPO_IMPIANTO     NUMBER(3) NOT NULL,
       DESCR                VARCHAR2(50) NULL
)
       TABLESPACE SICEE_SMALL_TBL
;


ALTER TABLE SICEE_D_TIPO_IMPIANTO
       ADD  ( CONSTRAINT PK_SICEE_D_TIPO_IMPIANTO PRIMARY KEY (
              ID_TIPO_IMPIANTO)
       USING INDEX
              TABLESPACE SICEE_SMALL_IDX ) ;


CREATE TABLE SICEE_D_TIPO_PAGAMENTO (
       ID_TIPO_PAGAMENTO    NUMBER(3) NOT NULL,
       DESCR                VARCHAR2(50) NULL,
       FLG_PAGAM_ATTIVO     CHAR(1) NULL
)
       TABLESPACE SICEE_SMALL_TBL
;


ALTER TABLE SICEE_D_TIPO_PAGAMENTO
       ADD  ( CONSTRAINT PK_SICEE_D_TIPO_PAGAMENTO PRIMARY KEY (
              ID_TIPO_PAGAMENTO)
       USING INDEX
              TABLESPACE SICEE_SMALL_IDX ) ;


CREATE TABLE SICEE_D_TIPO_REGOLAZIONE (
       ID_TIPO_REG          NUMBER(3) NOT NULL,
       DESCR                VARCHAR2(50) NULL
)
       TABLESPACE SICEE_SMALL_TBL
;


ALTER TABLE SICEE_D_TIPO_REGOLAZIONE
       ADD  ( CONSTRAINT PK_SICEE_D_TIPO_REGOLAZIONE PRIMARY KEY (
              ID_TIPO_REG)
       USING INDEX
              TABLESPACE SICEE_SMALL_IDX ) ;


CREATE TABLE SICEE_D_TITOLO (
       ID_TITOLO            VARCHAR2(3) NOT NULL,
       DESCR                VARCHAR2(50) NULL,
       FLG_EDIFICI          CHAR(1) NULL,
       FLG_IMPIANTI         CHAR(1) NULL,
       SIGLA                VARCHAR2(5) NULL
)
       TABLESPACE SICEE_SMALL_TBL
;


ALTER TABLE SICEE_D_TITOLO
       ADD  ( CONSTRAINT PK_SICEE_D_TITOLO PRIMARY KEY (ID_TITOLO)
       USING INDEX
              TABLESPACE SICEE_SMALL_IDX ) ;


CREATE TABLE SICEE_R_CERT_RUOLI (
       ID_CERTIFICATORE     VARCHAR2(5) NOT NULL,
       PROGR                VARCHAR2(4) NOT NULL,
       ANNO                 VARCHAR2(4) NOT NULL,
       FK_RUOLO_EDIFICIO    NUMBER(6) NOT NULL
)
       TABLESPACE SICEE_SMALL_TBL
;


ALTER TABLE SICEE_R_CERT_RUOLI
       ADD  ( CONSTRAINT PK_SICEE_R_CERT_RUOLI PRIMARY KEY (
              ID_CERTIFICATORE, PROGR, ANNO, FK_RUOLO_EDIFICIO)
       USING INDEX
              TABLESPACE SICEE_SMALL_IDX ) ;


CREATE TABLE SICEE_R_DEST_CLASSE (
       ID_CLASSE            NUMBER(3) NOT NULL,
       ID_DEST_USO          NUMBER(3) NOT NULL,
       MIN                  NUMBER(3) NULL,
       MAX                  NUMBER(3) NULL
);


ALTER TABLE SICEE_R_DEST_CLASSE
       ADD  ( CONSTRAINT PK_SICEE_R_DEST_CLASSE PRIMARY KEY (
              ID_CLASSE, ID_DEST_USO)
       USING INDEX
              TABLESPACE SICEE_SMALL_IDX ) ;


CREATE TABLE SICEE_T_ALTRE_INFO (
       ID_CERTIFICATORE     VARCHAR2(5) NOT NULL,
       PRESTAZIONE_ENE      NUMBER(5,2) NULL,
       PROGR_CERTIFICATO    VARCHAR2(4) NOT NULL,
       ANNO                 VARCHAR2(4) NOT NULL,
       LIMITE_NORMA_RISC    NUMBER(5,2) NULL,
       FK_CLASSE_192_05     NUMBER(3) NULL,
       FK_QUALITA_INVO      NUMBER(3) NULL,
       FK_MOTIVO            NUMBER(3) NULL,
       LIMITE_NORMA_IMP     NUMBER(5,2) NULL,
       VALORE_PREST_PDC     NUMBER(6) NULL,
       LIMITE_NORMA_PDC     NUMBER(5,2) NULL,
       ULT_INFO             VARCHAR2(500) NULL,
       METODOLOGIA_CALCOLO  VARCHAR2(100) NULL,
       NOME_PRODUTTORE      VARCHAR2(100) NULL,
       SW_UTILIZZATO        VARCHAR2(100) NULL,
       UNI_TS_11300         VARCHAR2(100) NULL
)
       TABLESPACE SICEE_SMALL_TBL
;


ALTER TABLE SICEE_T_ALTRE_INFO
       ADD  ( CONSTRAINT PK_SICEE_T_ALTRE_INFO PRIMARY KEY (
              ID_CERTIFICATORE, PROGR_CERTIFICATO, ANNO)
       USING INDEX
              TABLESPACE SICEE_SMALL_IDX ) ;


CREATE TABLE SICEE_T_AZIENDA (
       ID_AZIENDA           NUMBER NOT NULL,
       DENOMINAZIONE        VARCHAR2(50) NULL,
       ID_INDIRIZZO         NUMBER(6) NULL,
       DESC_INDIRIZZO       VARCHAR2(100) NULL,
       CAP                  VARCHAR2(5) NULL,
       ID_COMUNE            VARCHAR2(6) NULL,
       DESC_COMUNE          VARCHAR2(100) NULL,
       P_IVA                VARCHAR2(11) NULL,
       ID_PROV              VARCHAR2(6) NULL,
       DESC_PROV            VARCHAR2(50) NULL,
       ID_REGIONE           VARCHAR2(6) NULL,
       DESC_REGIONE         VARCHAR2(50) NULL,
       NUM_CIVICO           VARCHAR2(10) NULL
)
       TABLESPACE SICEE_SMALL_TBL
;


ALTER TABLE SICEE_T_AZIENDA
       ADD  ( CONSTRAINT PK_SICEE_T_AZIENDA PRIMARY KEY (ID_AZIENDA)
       USING INDEX
              TABLESPACE SICEE_SMALL_IDX ) ;


CREATE TABLE SICEE_T_CERTIFICATO (
       ID_CERTIFICATORE     VARCHAR2(5) NOT NULL,
       PROGR_CERTIFICATO    VARCHAR2(4) NOT NULL,
       ANNO                 VARCHAR2(4) NOT NULL,
       DT_SCADENZA          DATE NULL,
       FK_TRANSAZIONE_ACE   NUMBER NOT NULL,
       DT_ACQUISTO          DATE NULL,
       FK_STATO             NUMBER(3) NULL,
       FK_DICHIARAZIONE     NUMBER(3) NULL,
       FLG_DICHIARAZIONE    CHAR(1) NULL,
       ID_INDIRIZZO         NUMBER(6) NULL,
       DESC_INDIRIZZO       VARCHAR2(30) NULL,
       DT_INIZIO            DATE NULL,
       CAP                  VARCHAR2(5) NULL,
       ID_COMUNE            VARCHAR2(6) NULL,
       DESC_COMUNE          VARCHAR2(50) NULL,
       SEZIONE              VARCHAR2(5) NULL,
       ID_PROV              VARCHAR2(6) NULL,
       FOGLIO               VARCHAR2(5) NULL,
       DESC_PROV            VARCHAR2(50) NULL,
       ID_REGIONE           VARCHAR2(6) NULL,
       PARTICELLA           VARCHAR2(5) NULL,
       SUBALTERNO           VARCHAR2(3) NULL,
       DESC_REGIONE         VARCHAR2(50) NULL,
       PIANO                NUMBER(3) NULL,
       NUM_PIANI_COMPLESSIVI NUMBER(3) NULL,
       NUM_APPARTAMENTI     NUMBER(3) NULL,
       SCALA                VARCHAR2(10) NULL,
       INTERNO              VARCHAR2(10) NULL,
       NOTE                 VARCHAR2(500) NULL,
       FOTO                 BLOB NULL,
       FLG_STAMPA_DEF       CHAR(1) NULL,
       NOME_ACE_FIRMATO     VARCHAR2(20) NULL,
       ACE_FIRMATO          BLOB NULL,
       NOME_COCERTIFICATORE VARCHAR2(20) NULL,
       COGNOME_COCERTIFICATORE VARCHAR2(50) NULL,
       NUM_COCERTIFICATORE  VARCHAR2(5) NULL
)
       TABLESPACE SICEE_SMALL_TBL
;


ALTER TABLE SICEE_T_CERTIFICATO
       ADD  ( CONSTRAINT PK_SICEE_T_CERTIFICATO PRIMARY KEY (
              ID_CERTIFICATORE, PROGR_CERTIFICATO, ANNO)
       USING INDEX
              TABLESPACE SICEE_SMALL_IDX ) ;


CREATE TABLE SICEE_T_CERTIFICATORE (
       ID_CERTIFICATORE     VARCHAR2(5) NOT NULL,
       FK_AZIENDA           NUMBER NULL,
       FK_TITOLO            VARCHAR2(3) NULL,
       NOME                 VARCHAR2(30) NULL,
       COGNOME              VARCHAR2(50) NULL,
       CODICE_FISCALE       VARCHAR2(16) NULL,
       ID_COMUNE_NASCITA    VARCHAR2(6) NULL,
       DESC_COMUNE_NASCITA  VARCHAR2(100) NULL,
       DT_NASCITA           DATE NULL,
       ID_PROV_NASCITA      VARCHAR2(6) NULL,
       ID_INDIRIZZO         NUMBER(6) NULL,
       DESC_PROV_NASCITA    VARCHAR2(50) NULL,
       ID_REGIONE_NASCITA   VARCHAR2(6) NULL,
       DESC_INDIRIZZO       VARCHAR2(100) NULL,
       CAP                  VARCHAR2(5) NULL,
       DESC_REGIONE_NASCITA VARCHAR2(50) NULL,
       ID_COMUNE_RESIDENZA  VARCHAR2(6) NULL,
       NUM_CIVICO_RESIDENZA VARCHAR2(10) NULL,
       DESC_COMUNE_RESIDENZA VARCHAR2(50) NULL,
       FLG_EDIFICI          CHAR(1) NULL,
       FLG_IMPIANTI         CHAR(1) NULL,
       FLG_VERIFICATO       CHAR(1) NULL,
       FLG_PAGAMENTO        CHAR(1) NULL,
       NOTE                 VARCHAR2(500) NULL,
       ID_PROV_RESIDENZA    VARCHAR2(6) NULL,
       DT_ISCR_ELENCO       DATE NULL,
       DESC_PROV_RESIDENZA  VARCHAR2(50) NULL,
       DT_SCADENZA_ELENCO   DATE NULL,
       ID_REGIONE_RESIDENZA VARCHAR2(6) NULL,
       NUM_TOT_ACE          NUMBER NULL,
       DESC_REGIONE_RESIDENZA VARCHAR2(50) NULL,
       ORDINE               VARCHAR2(30) NULL,
       DESC_PROV_ORDINE     VARCHAR2(30) NULL,
       NUM_ISCR_ALBO        VARCHAR2(20) NULL,
       ID_PROV_ORDINE       VARCHAR2(6) NULL,
       SETTORE              VARCHAR2(50) NULL,
       SEZIONE              VARCHAR2(50) NULL,
       TELEFONO             VARCHAR2(20) NULL,
       DATA_ISCR_ALBO       DATE NULL,
       FAX                  VARCHAR2(30) NULL,
       CELL                 VARCHAR2(20) NULL,
       EMAIL                VARCHAR2(30) NULL,
       NUM_CERTIFICATORE    VARCHAR2(10) NULL
)
       TABLESPACE SICEE_SMALL_TBL
;


ALTER TABLE SICEE_T_CERTIFICATORE
       ADD  ( CONSTRAINT PK_SICEE_T_CERTIFICATORE PRIMARY KEY (
              ID_CERTIFICATORE)
       USING INDEX
              TABLESPACE SICEE_SMALL_IDX ) ;


CREATE TABLE SICEE_T_CLASSE_ENERGETICA (
       IND_RISC_EPI         NUMBER(5,2) NULL,
       ID_CERTIFICATORE     VARCHAR2(5) NOT NULL,
       IND_COND_EST         NUMBER(5,2) NULL,
       PROGR_CERTIFICATO    VARCHAR2(4) NOT NULL,
       IND_ILLUM            NUMBER(5,2) NULL,
       ANNO                 VARCHAR2(4) NOT NULL,
       IND_GLOB_EPLORDO     NUMBER(5,2) NULL,
       FK_CLASSE            NUMBER(3) NOT NULL,
       REND_GENER           NUMBER(5,2) NULL,
       REND_REGOL           NUMBER(5,2) NULL,
       SERVIZI_ENERGETICI   VARCHAR2(100) NULL,
       PERC_FONTI_RINNOV    NUMBER(5,2) NULL,
       REND_EMISS           NUMBER(5,2) NULL,
       REND_DISTRIB         NUMBER(5,2) NULL,
       REND_IMP_ETAG        NUMBER(5,2) NULL,
       DOM_RISC_QHTO        NUMBER(5) NULL,
       LIMITE_REG_QHTO      NUMBER(6) NULL,
       IND_RISC_EPITO       NUMBER(5,2) NULL,
       DOM_ACS_QHWTO        NUMBER(6) NULL,
       EN_ACS_RINNO_TO      NUMBER(6) NULL,
       REND_ACS_ETAG_ACSTO  NUMBER(5,2) NULL,
       FABB_ACS_TO          NUMBER(5,2) NULL,
       IND_GLOB_EPLORDO_TO  NUMBER(5,2) NULL,
       ETAG_CONV            NUMBER(5,2) NULL,
       IND_GLOB_LIMITE_TO   NUMBER(5,2) NULL
)
       TABLESPACE SICEE_SMALL_TBL
;


ALTER TABLE SICEE_T_CLASSE_ENERGETICA
       ADD  ( CONSTRAINT PK_SICEE_T_CLASSE_ENERGETICA PRIMARY KEY (
              ID_CERTIFICATORE, PROGR_CERTIFICATO, ANNO)
       USING INDEX
              TABLESPACE SICEE_SMALL_IDX ) ;


CREATE TABLE SICEE_T_CONSUMI_EDIFICIO (
       ID_CERTIFICATORE     VARCHAR2(5) NOT NULL,
       PROGR_CERTIFICATO    VARCHAR2(4) NOT NULL,
       ANNO                 VARCHAR2(4) NOT NULL,
       FK_TIPO_EROG         NUMBER(3) NULL,
       FK_TIPO_IMPIANTO     NUMBER(3) NULL,
       FK_TIPO_DISTRIB      NUMBER(3) NULL,
       FK_TIPO_REG          NUMBER(3) NULL,
       ANN_TERMI_FOSSILE    NUMBER(6) NULL,
       ANN_ELETT_FOSSILE    NUMBER(6) NULL,
       ANN_TERMI_RINNO      NUMBER(6) NULL,
       ANN_ELETT_RINNO      NUMBER(6) NULL,
       COMPLESS_TERMICO     NUMBER(6) NULL,
       COMPLESS_ELETTRICO   NUMBER(6) NULL,
       UI_SERVITE           VARCHAR2(20) NULL,
       FLG_CONT_RIP         CHAR(1) NULL
)
       TABLESPACE SICEE_SMALL_TBL
;


ALTER TABLE SICEE_T_CONSUMI_EDIFICIO
       ADD  ( CONSTRAINT PK_SICEE_T_CONSUMI_EDIFICIO PRIMARY KEY (
              ID_CERTIFICATORE, PROGR_CERTIFICATO, ANNO)
       USING INDEX
              TABLESPACE SICEE_SMALL_IDX ) ;


CREATE TABLE SICEE_T_DATI_GENERALI (
       ID_CERTIFICATORE     VARCHAR2(5) NOT NULL,
       PROGR_CERTIFICATO    VARCHAR2(4) NOT NULL,
       ANNO                 VARCHAR2(4) NOT NULL,
       FK_TIPO_EDIFICIO     NUMBER(3) NOT NULL,
       FK_DEST_USO          NUMBER(3) NOT NULL,
       ANNO_COSTRUZIONE     NUMBER(4) NULL,
       ANNO_ULT_RIST        NUMBER(4) NULL,
       VOL_LORDO_RISCALDATO NUMBER(9) NULL,
       SUP_DISPERDENTE_TOT  NUMBER(6) NULL,
       FATTORE_FORMA        NUMBER(7,4) NULL,
       TRASM_OPACHE         NUMBER(6,3) NULL,
       TRASM_TRASP          NUMBER(6,3) NULL,
       ZONA_CLIMATICA       CHAR(1) NULL,
       GRADI_GIORNO         NUMBER(4) NULL,
       SU                   NUMBER(6) NULL,
       EMISSIONI_SERRA      NUMBER(5) NULL,
       ETTARI_BOSCO         NUMBER(5) NULL
)
       TABLESPACE SICEE_SMALL_TBL
;


ALTER TABLE SICEE_T_DATI_GENERALI
       ADD  ( CONSTRAINT PK_SICEE_T_DATI_GENERALI PRIMARY KEY (
              ID_CERTIFICATORE, PROGR_CERTIFICATO, ANNO)
       USING INDEX
              TABLESPACE SICEE_SMALL_IDX ) ;


CREATE TABLE SICEE_T_ENERGIA_SOPR_INGR (
       ID_CERTIFICATORE     VARCHAR2(5) NOT NULL,
       PROGR_CERTIFICATO    VARCHAR2(4) NOT NULL,
       ANNO                 VARCHAR2(4) NOT NULL,
       FK_DATI              NUMBER(3) NULL,
       TECNO_RINNO          VARCHAR2(500) NULL,
       ANNO_INSTALL         NUMBER NULL,
       EN_TERMICA_PROD      NUMBER(9) NULL,
       EN_ELETT_PROD        NUMBER(9) NULL,
       AUTOCONS_TERMICO     NUMBER(5,2) NULL,
       AUTOCONS_ELETT       NUMBER(5,2) NULL,
       DT_SOPRALLUOGO       DATE NULL,
       NOTE_SOPRALL         VARCHAR2(500) NULL
)
       TABLESPACE SICEE_SMALL_TBL
;


ALTER TABLE SICEE_T_ENERGIA_SOPR_INGR
       ADD  ( CONSTRAINT PK_SICEE_T_ENERGIA_SOPR PRIMARY KEY (
              ID_CERTIFICATORE, PROGR_CERTIFICATO, ANNO)
       USING INDEX
              TABLESPACE SICEE_SMALL_IDX ) ;


CREATE TABLE SICEE_T_FABBISOGNO (
       ID_CERTIFICATORE     VARCHAR2(5) NOT NULL,
       PROGR_CERTIFICATO    VARCHAR2(4) NOT NULL,
       ANNO                 VARCHAR2(4) NOT NULL,
       DOM_RISC_QH          NUMBER(6) NULL,
       LIMITE_REG_QH_LIM    NUMBER(6) NULL,
       FABB_CONDIZ          NUMBER(6) NULL,
       DOM_ACS_QHW          NUMBER(6) NULL,
       EN_ACS_RINNO         NUMBER(6) NULL,
       REND_ACS_ETAGACS     NUMBER(5,2) NULL,
       FABB_ACS             NUMBER(5,2) NULL,
       FABB_ILLUM           NUMBER(5,2) NULL
)
       TABLESPACE SICEE_SMALL_TBL
;


ALTER TABLE SICEE_T_FABBISOGNO
       ADD  ( CONSTRAINT PK_SICEE_T_FABBISOGNO PRIMARY KEY (
              ID_CERTIFICATORE, PROGR_CERTIFICATO, ANNO)
       USING INDEX
              TABLESPACE SICEE_SMALL_IDX ) ;


CREATE TABLE SICEE_T_IMP_RISCALDAMENTO_ACS (
       ID_CERTIFICATORE     VARCHAR2(5) NOT NULL,
       PROGR                VARCHAR2(4) NOT NULL,
       ANNO                 VARCHAR2(4) NOT NULL,
       FLG_BOLLINO          CHAR(1) NULL,
       FK_CLASSE_EFF_RISC   NUMBER(3) NULL,
       CODICE_IMPIANTO      VARCHAR2(50) NULL,
       FK_CLASSE_EFF_ACS    NUMBER(3) NULL,
       FK_COMBUSTIBILE_RISC NUMBER(3) NULL,
       NUMERO_BOLLINO       VARCHAR2(20) NULL,
       GEN_ANNO_RISC        NUMBER(4) NULL,
       FK_COMBUSTIBILE_ACS  NUMBER(3) NULL,
       POT_RISCALDAMENTO    NUMBER(6) NULL,
       GEN_ANNO_ACS         NUMBER(4) NULL,
       POT_ACS              NUMBER(6) NULL
)
       TABLESPACE SICEE_SMALL_TBL
;


ALTER TABLE SICEE_T_IMP_RISCALDAMENTO_ACS
       ADD  ( CONSTRAINT PK_SICEE_T_IMP_RISCALDAMENTO PRIMARY KEY (
              ID_CERTIFICATORE, PROGR, ANNO)
       USING INDEX
              TABLESPACE SICEE_SMALL_IDX ) ;


CREATE TABLE SICEE_T_LIMITEQH_PIEMONTE (
       VOLUME               NUMBER(6) NULL,
       GG_3000              NUMBER(4) NULL,
       GG_5000              NUMBER(4) NULL
);


CREATE TABLE SICEE_T_RACCOMANDAZIONI (
       ID_CERTIFICATORE     VARCHAR2(5) NOT NULL,
       PROGR_CERTIFICATO    VARCHAR2(4) NOT NULL,
       ANNO                 VARCHAR2(4) NOT NULL,
       PRIORITA             VARCHAR2(20) NOT NULL,
       SISTEMA              VARCHAR2(20) NOT NULL,
       INTERVENTO           VARCHAR2(100) NULL,
       TEMPO_RITORNO        VARCHAR2(50) NULL
)
       TABLESPACE SICEE_SMALL_TBL
;


ALTER TABLE SICEE_T_RACCOMANDAZIONI
       ADD  ( CONSTRAINT PK_SICEE_T_RACCOMANDAZIONI PRIMARY KEY (
              ID_CERTIFICATORE, PROGR_CERTIFICATO, ANNO, PRIORITA, 
              SISTEMA)
       USING INDEX
              TABLESPACE SICEE_SMALL_IDX ) ;


CREATE TABLE SICEE_T_RISPETTO_NORMATIVE (
       DT_TITOLO            DATE NULL,
       ID_CERTIFICATORE     VARCHAR2(5) NOT NULL,
       PROGR_CERTIFICATO    VARCHAR2(4) NOT NULL,
       ANNO                 VARCHAR2(4) NOT NULL,
       FK_NORMA             NUMBER(3) NULL,
       FLG_NORMA            CHAR(1) NULL,
       MOTIVO_NON_CONFORMITA VARCHAR2(500) NULL,
       NOTE                 VARCHAR2(500) NULL
)
       TABLESPACE SICEE_SMALL_TBL
;


ALTER TABLE SICEE_T_RISPETTO_NORMATIVE
       ADD  ( CONSTRAINT PK_SICEE_T_RISPETTO_NORMATIVE PRIMARY KEY (
              ID_CERTIFICATORE, PROGR_CERTIFICATO, ANNO)
       USING INDEX
              TABLESPACE SICEE_SMALL_IDX ) ;


CREATE TABLE SICEE_T_RUOLI_EDIFICIO (
       ID_RUOLO_EDIFICIO    NUMBER(6) NOT NULL,
       FK_TIPO_RUOLO        NUMBER(3) NOT NULL,
       NOME                 VARCHAR2(30) NULL,
       COGNOME              VARCHAR2(50) NULL,
       ID_INDIRIZZO         NUMBER(6) NULL,
       DESC_INDIRIZZO       VARCHAR2(30) NULL,
       CAP                  VARCHAR2(5) NULL,
       ID_COMUNE            VARCHAR2(6) NULL,
       DESC_COMUNE          VARCHAR2(50) NULL,
       TELEFONO             VARCHAR2(20) NULL,
       FAX                  VARCHAR2(30) NULL,
       CELL                 VARCHAR2(20) NULL,
       EMAIL                VARCHAR2(30) NULL
)
       TABLESPACE SICEE_SMALL_TBL
;


ALTER TABLE SICEE_T_RUOLI_EDIFICIO
       ADD  ( CONSTRAINT PK_SICEE_T_RUOLI_EDIFICIO PRIMARY KEY (
              ID_RUOLO_EDIFICIO)
       USING INDEX
              TABLESPACE SICEE_SMALL_IDX ) ;


CREATE TABLE SICEE_T_TRANSAZIONE_ACE (
       ID_TRANSAZIONE_ACE   NUMBER NOT NULL,
       FK_TIPO_PAGAMENTO    NUMBER(3) NOT NULL,
       NUM_TRANSAZIONE      VARCHAR2(30) NULL,
       DATA_TRANSAZIONE     DATE NULL,
       FLG_VERIFICATO       CHAR(1) NULL,
       ESEGUITO_NOME        VARCHAR2(30) NULL,
       ESEGUITO_COGNOME     VARCHAR2(50) NULL
)
       TABLESPACE SICEE_SMALL_TBL
;


ALTER TABLE SICEE_T_TRANSAZIONE_ACE
       ADD  ( CONSTRAINT PK_SICEE_T_TRANSAZIONE_ACE PRIMARY KEY (
              ID_TRANSAZIONE_ACE)
       USING INDEX
              TABLESPACE SICEE_SMALL_IDX ) ;


CREATE TABLE SICEE_T_TRANSAZIONE_REGISTRAZ (
       ID_TRANSAZIONE_REG   NUMBER NOT NULL,
       FK_CERTIFICATORE     VARCHAR2(5) NOT NULL,
       FK_TIPO_PAGAMENTO    NUMBER(3) NOT NULL,
       DATA_TRANSAZIONE     DATE NULL,
       NUM_TRANSAZIONE      VARCHAR2(30) NULL,
       FLG_VERIFICATO       CHAR(1) NULL,
       ESEGUITO_NOME        VARCHAR2(30) NULL,
       ESEGUITO_COGNOME     VARCHAR2(50) NULL
)
       TABLESPACE SICEE_SMALL_TBL
;


ALTER TABLE SICEE_T_TRANSAZIONE_REGISTRAZ
       ADD  ( CONSTRAINT PK_SICEE_T_TRANSAZIONE_REGISTR PRIMARY KEY (
              ID_TRANSAZIONE_REG)
       USING INDEX
              TABLESPACE SICEE_SMALL_IDX ) ;


ALTER TABLE SICEE_R_CERT_RUOLI
       ADD  ( CONSTRAINT FK_SICEE_T_CERTIFICATO_09
              FOREIGN KEY (ID_CERTIFICATORE, PROGR, ANNO)
                             REFERENCES SICEE_T_CERTIFICATO ) ;


ALTER TABLE SICEE_R_CERT_RUOLI
       ADD  ( CONSTRAINT FK_SICEE_T_RUOLI_EDIF_01
              FOREIGN KEY (FK_RUOLO_EDIFICIO)
                             REFERENCES SICEE_T_RUOLI_EDIFICIO ) ;


ALTER TABLE SICEE_R_DEST_CLASSE
       ADD  ( CONSTRAINT R_55
              FOREIGN KEY (ID_CLASSE)
                             REFERENCES SICEE_D_CLASSE_ENERGETICA ) ;


ALTER TABLE SICEE_R_DEST_CLASSE
       ADD  ( CONSTRAINT R_54
              FOREIGN KEY (ID_DEST_USO)
                             REFERENCES SICEE_D_DEST_USO ) ;


ALTER TABLE SICEE_T_ALTRE_INFO
       ADD  ( CONSTRAINT FK_SICEE_D_MOTIVO_01
              FOREIGN KEY (FK_MOTIVO)
                             REFERENCES SICEE_D_MOTIVO_RILASCIO ) ;


ALTER TABLE SICEE_T_ALTRE_INFO
       ADD  ( CONSTRAINT FK_SICEE_D_QUALITA_01
              FOREIGN KEY (FK_QUALITA_INVO)
                             REFERENCES SICEE_D_QUALITA_INVOLUCRO ) ;


ALTER TABLE SICEE_T_ALTRE_INFO
       ADD  ( CONSTRAINT FK_SICEE_D_CLASSE_ENE_02
              FOREIGN KEY (FK_CLASSE_192_05)
                             REFERENCES SICEE_D_CLASSE_ENERGETICA ) ;


ALTER TABLE SICEE_T_ALTRE_INFO
       ADD  ( CONSTRAINT FK_SICEE_T_CERTIFICATO_06
              FOREIGN KEY (ID_CERTIFICATORE, PROGR_CERTIFICATO, ANNO)
                             REFERENCES SICEE_T_CERTIFICATO ) ;


ALTER TABLE SICEE_T_CERTIFICATO
       ADD  ( CONSTRAINT FK_SICEE_T_TRANSAZIONE_01
              FOREIGN KEY (FK_TRANSAZIONE_ACE)
                             REFERENCES SICEE_T_TRANSAZIONE_ACE ) ;


ALTER TABLE SICEE_T_CERTIFICATO
       ADD  ( CONSTRAINT R_53
              FOREIGN KEY (FK_STATO)
                             REFERENCES SICEE_D_STATO_CERT ) ;


ALTER TABLE SICEE_T_CERTIFICATO
       ADD  ( CONSTRAINT FK_SICEE_D_DICHIARAZIONE_01
              FOREIGN KEY (FK_DICHIARAZIONE)
                             REFERENCES SICEE_D_DICHIARAZIONE ) ;


ALTER TABLE SICEE_T_CERTIFICATO
       ADD  ( CONSTRAINT FK_SICEE_T_CERTIFICATORE_01
              FOREIGN KEY (ID_CERTIFICATORE)
                             REFERENCES SICEE_T_CERTIFICATORE ) ;


ALTER TABLE SICEE_T_CERTIFICATORE
       ADD  ( CONSTRAINT FK_SICEE_D_TITOLO_01
              FOREIGN KEY (FK_TITOLO)
                             REFERENCES SICEE_D_TITOLO ) ;


ALTER TABLE SICEE_T_CERTIFICATORE
       ADD  ( CONSTRAINT FK_SICEE_T_AZIENDA_01
              FOREIGN KEY (FK_AZIENDA)
                             REFERENCES SICEE_T_AZIENDA ) ;


ALTER TABLE SICEE_T_CLASSE_ENERGETICA
       ADD  ( CONSTRAINT FK_SICEE_D_CLASSE_ENE_01
              FOREIGN KEY (FK_CLASSE)
                             REFERENCES SICEE_D_CLASSE_ENERGETICA ) ;


ALTER TABLE SICEE_T_CLASSE_ENERGETICA
       ADD  ( CONSTRAINT FK_SICEE_T_CERTIFICATO_07
              FOREIGN KEY (ID_CERTIFICATORE, PROGR_CERTIFICATO, ANNO)
                             REFERENCES SICEE_T_CERTIFICATO ) ;


ALTER TABLE SICEE_T_CONSUMI_EDIFICIO
       ADD  ( CONSTRAINT FK_SICEE_D_TIPO_REGOL_01
              FOREIGN KEY (FK_TIPO_REG)
                             REFERENCES SICEE_D_TIPO_REGOLAZIONE ) ;


ALTER TABLE SICEE_T_CONSUMI_EDIFICIO
       ADD  ( CONSTRAINT FK_SICEE_D_TIPO_DISTR_01
              FOREIGN KEY (FK_TIPO_DISTRIB)
                             REFERENCES SICEE_D_TIPO_DISTRIB ) ;


ALTER TABLE SICEE_T_CONSUMI_EDIFICIO
       ADD  ( CONSTRAINT FK_SICEE_D_TIPO_EROG_01
              FOREIGN KEY (FK_TIPO_EROG)
                             REFERENCES SICEE_D_TIPO_EROGAZIONE ) ;


ALTER TABLE SICEE_T_CONSUMI_EDIFICIO
       ADD  ( CONSTRAINT FK_SICEE_D_TIPO_IMP_01
              FOREIGN KEY (FK_TIPO_IMPIANTO)
                             REFERENCES SICEE_D_TIPO_IMPIANTO ) ;


ALTER TABLE SICEE_T_CONSUMI_EDIFICIO
       ADD  ( CONSTRAINT FK_SICEE_T_CERTIFICATO_05
              FOREIGN KEY (ID_CERTIFICATORE, PROGR_CERTIFICATO, ANNO)
                             REFERENCES SICEE_T_CERTIFICATO ) ;


ALTER TABLE SICEE_T_DATI_GENERALI
       ADD  ( CONSTRAINT FK_SICEE_D_TIPO_EDIFIC_01
              FOREIGN KEY (FK_TIPO_EDIFICIO)
                             REFERENCES SICEE_D_TIPO_EDIFICIO ) ;


ALTER TABLE SICEE_T_DATI_GENERALI
       ADD  ( CONSTRAINT FK_SICEE_D_DEST_01
              FOREIGN KEY (FK_DEST_USO)
                             REFERENCES SICEE_D_DEST_USO ) ;


ALTER TABLE SICEE_T_DATI_GENERALI
       ADD  ( CONSTRAINT FK_SICEE_T_CERTIFICATO_03
              FOREIGN KEY (ID_CERTIFICATORE, PROGR_CERTIFICATO, ANNO)
                             REFERENCES SICEE_T_CERTIFICATO ) ;


ALTER TABLE SICEE_T_ENERGIA_SOPR_INGR
       ADD  ( CONSTRAINT FK_SICEE_T_CERTIFICATO_04
              FOREIGN KEY (ID_CERTIFICATORE, PROGR_CERTIFICATO, ANNO)
                             REFERENCES SICEE_T_CERTIFICATO ) ;


ALTER TABLE SICEE_T_ENERGIA_SOPR_INGR
       ADD  ( CONSTRAINT FK_SICEE_D_DATI_01
              FOREIGN KEY (FK_DATI)
                             REFERENCES SICEE_D_DATI_INGRESSO ) ;


ALTER TABLE SICEE_T_FABBISOGNO
       ADD  ( CONSTRAINT FK_SICEE_T_CERTIFICATO_08
              FOREIGN KEY (ID_CERTIFICATORE, PROGR_CERTIFICATO, ANNO)
                             REFERENCES SICEE_T_CERTIFICATO ) ;


ALTER TABLE SICEE_T_IMP_RISCALDAMENTO_ACS
       ADD  ( CONSTRAINT FK_SICEE_D_COMB_01
              FOREIGN KEY (FK_COMBUSTIBILE_ACS)
                             REFERENCES SICEE_D_COMBUSTIBILE ) ;


ALTER TABLE SICEE_T_IMP_RISCALDAMENTO_ACS
       ADD  ( CONSTRAINT FK_SICEE_D_COMB_02
              FOREIGN KEY (FK_COMBUSTIBILE_RISC)
                             REFERENCES SICEE_D_COMBUSTIBILE ) ;


ALTER TABLE SICEE_T_IMP_RISCALDAMENTO_ACS
       ADD  ( CONSTRAINT FK_SICEE_D_CLASSE_EFF_02
              FOREIGN KEY (FK_CLASSE_EFF_ACS)
                             REFERENCES SICEE_D_CLASSE_EFFICIENZA ) ;


ALTER TABLE SICEE_T_IMP_RISCALDAMENTO_ACS
       ADD  ( CONSTRAINT FK_SICEE_D_CLASSE_EFF_01
              FOREIGN KEY (FK_CLASSE_EFF_RISC)
                             REFERENCES SICEE_D_CLASSE_EFFICIENZA ) ;


ALTER TABLE SICEE_T_IMP_RISCALDAMENTO_ACS
       ADD  ( CONSTRAINT FK_SICEE_T_CERTIFICATO_01
              FOREIGN KEY (ID_CERTIFICATORE, PROGR, ANNO)
                             REFERENCES SICEE_T_CERTIFICATO ) ;


ALTER TABLE SICEE_T_RACCOMANDAZIONI
       ADD  ( CONSTRAINT FK_SICEE_T_CERTIFICATO_10
              FOREIGN KEY (ID_CERTIFICATORE, PROGR_CERTIFICATO, ANNO)
                             REFERENCES SICEE_T_CERTIFICATO ) ;


ALTER TABLE SICEE_T_RACCOMANDAZIONI
       ADD  ( CONSTRAINT FK_SICEE_D_PRIORITA_01
              FOREIGN KEY (PRIORITA)
                             REFERENCES SICEE_D_PRIORITA ) ;


ALTER TABLE SICEE_T_RACCOMANDAZIONI
       ADD  ( CONSTRAINT FK_SICEE_D_SISTEMA_01
              FOREIGN KEY (SISTEMA)
                             REFERENCES SICEE_D_SISTEMA_RACC ) ;


ALTER TABLE SICEE_T_RISPETTO_NORMATIVE
       ADD  ( CONSTRAINT FK_SICEE_T_CERTIFICATO_02
              FOREIGN KEY (ID_CERTIFICATORE, PROGR_CERTIFICATO, ANNO)
                             REFERENCES SICEE_T_CERTIFICATO ) ;


ALTER TABLE SICEE_T_RISPETTO_NORMATIVE
       ADD  ( CONSTRAINT FK_SICEE_D_NORMATIVA_01
              FOREIGN KEY (FK_NORMA)
                             REFERENCES SICEE_D_NORMATIVA ) ;


ALTER TABLE SICEE_T_RUOLI_EDIFICIO
       ADD  ( CONSTRAINT FK_SICEE_D_RUOLO_01
              FOREIGN KEY (FK_TIPO_RUOLO)
                             REFERENCES SICEE_D_RUOLO ) ;


ALTER TABLE SICEE_T_TRANSAZIONE_ACE
       ADD  ( CONSTRAINT FK_SICEE_D_TIPO_PAGAMENTO_02
              FOREIGN KEY (FK_TIPO_PAGAMENTO)
                             REFERENCES SICEE_D_TIPO_PAGAMENTO ) ;


ALTER TABLE SICEE_T_TRANSAZIONE_REGISTRAZ
       ADD  ( CONSTRAINT FK_SICEE_D_TIPO_PAGAMENTO_01
              FOREIGN KEY (FK_TIPO_PAGAMENTO)
                             REFERENCES SICEE_D_TIPO_PAGAMENTO ) ;


ALTER TABLE SICEE_T_TRANSAZIONE_REGISTRAZ
       ADD  ( CONSTRAINT FK_SICEE_T_CERTIFICATORE_02
              FOREIGN KEY (FK_CERTIFICATORE)
                             REFERENCES SICEE_T_CERTIFICATORE ) ;



